# Fancy Indexing

Fancy indexing (also called **advanced indexing**) allows you to select **multiple specific elements** of an array using **lists or arrays of indices**.

Unlike normal indexing, the indices **do not have to be consecutive**.

---

# Why use Fancy Indexing?

Normal indexing accesses **one element**.

```python
arr[2]
```

↓

```text
30
```

Fancy indexing accesses **multiple elements**.

```python
arr[[0,2,4]]
```

↓

```text
[10 30 50]
```

---

# 1D Fancy Indexing

## Syntax

```python
array[[index1, index2, index3, ...]]
```

---

## Example

```python
arr = np.array([10,20,30,40,50])

arr[[0,2,4]]
```

Output

```text
[10 30 50]
```

Notice

The indices

```
0
2
4
```

do not have to be consecutive.

---

## Repeated Indices

```python
arr[[2,2,1,4]]
```

Output

```text
[30 30 20 50]
```

Repeated indices are allowed.

---

## Negative Indices

```python
arr[[-1,-2]]
```

Output

```text
[50 40]
```

Negative indexing works exactly the same.

---

# 2D Fancy Indexing

Suppose

```python
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
```

---

## Select Entire Rows

```python
arr[[0,2]]
```

Output

```text
[[1 2 3]
 [7 8 9]]
```

Rows 0 and 2 are selected.

---

## Select Individual Elements

```python
arr[[0,2],[1,0]]
```

Output

```text
[2 7]
```

Explanation

```
(0,1) → 2

(2,0) → 7
```

The first list represents row indices.

The second list represents column indices.

NumPy pairs them **element by element**.

```
(0,1)

(2,0)
```

---

Another Example

```python
arr[[0,1,2],[2,1,0]]
```

↓

```
(0,2)

(1,1)

(2,0)
```

Output

```text
[3 5 7]
```

---

# Selecting Rows and Columns Together

Suppose

```python
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
```

Rows

```python
arr[[0,2],:]
```

Output

```text
[[1 2 3]
 [7 8 9]]
```

---

Columns

```python
arr[:,[0,2]]
```

Output

```text
[[1 3]
 [4 6]
 [7 9]]
```

---

Rows and Columns

```python
arr[[0,2]][:,[0,2]]
```

Output

```text
[[1 3]
 [7 9]]
```

---

# Boolean Fancy Indexing (Masking)

Fancy indexing also includes **boolean indexing**.

```python
arr = np.array([1,2,3,4,5])

arr[arr > 3]
```

Output

```text
[4 5]
```

Another Example

```python
arr[arr % 2 == 0]
```

↓

```text
[2 4]
```

This is called **boolean masking**.

---

# Fancy Indexing Returns a Copy

Unlike slicing,

Fancy indexing returns a **copy**.

Example

```python
arr = np.array([1,2,3])

x = arr[[0,2]]

x[0] = 100
```

Original

```python
arr
```

still remains

```text
[1 2 3]
```

because `x` is a copy.

---

# Fancy Indexing vs Slicing

Suppose

```python
arr = np.array([10,20,30,40,50])
```

### Slicing

```python
arr[1:4]
```

↓

```text
[20 30 40]
```

Elements must be **continuous**.

---

### Fancy Indexing

```python
arr[[0,2,4]]
```

↓

```text
[10 30 50]
```

Elements can be selected in **any order**.

---

# Fancy Indexing vs Boolean Indexing

### Fancy Indexing

Uses **integer indices**.

```python
arr[[0,2,4]]
```

---

### Boolean Indexing

Uses **True/False values**.

```python
arr[arr > 3]
```

---

# Comparison

| Feature | Normal Indexing | Slicing | Fancy Indexing |
|----------|----------------|----------|----------------|
| Select one element | ✔ | ✖ | ✔ |
| Select continuous elements | ✖ | ✔ | ✔ |
| Select arbitrary elements | ✖ | ✖ | ✔ |
| Returns view | ✖ (scalar) | ✔ | ✖ (copy) |

---

# When should you use Fancy Indexing?

- Select arbitrary elements.
- Rearrange rows or columns.
- Duplicate elements using repeated indices.
- Boolean filtering (masking).
- Machine Learning data preprocessing.

---

# Remember

- Uses **lists or arrays of indices**.
- Indices can be in **any order**.
- Repeated indices are allowed.
- Negative indices work.
- Boolean indexing is a form of fancy indexing.
- Returns a **copy**, not a view.