---

# Broadcasting

## Introduction

The term broadcasting refers to the ability of NumPy to treat arrays of different shapes during arithmetic operations. Arithmetic operations on arrays are usually done on corresponding elements. If two arrays are of exactly the same shape, then these operations are smoothly performed.

If the dimensions of two arrays are dissimilar, element-to-element operations are not possible. However, operations on arrays of non-similar shapes is still possible in NumPy, because of the broadcasting capability. The smaller array is broadcast to the size of the larger array so that they have compatible shapes.

> **Remember:**  
> Broadcasting allows NumPy to perform operations on arrays with **different shapes** by making their shapes compatible.

---

## Basic Example of Broadcasting

```python
arr = np.array([1, 2, 3])

arr + 10
```

Output:

```text
[11 12 13]
```

Conceptually, NumPy treats the operation as:

```text
[1 2 3]
+
[10 10 10]
---------
[11 12 13]
```

The scalar `10` is **broadcast** across every element of the array.

> **Important:**  
> NumPy does not necessarily create an actual copy of `[10, 10, 10]`. This is a conceptual way of understanding what broadcasting does.

---

## Broadcasting Rules

NumPy compares the shapes of arrays **from right to left**.

Two dimensions are compatible when:

1. They are **equal**, or
2. One of them is **1**.

If neither condition is satisfied, broadcasting is not possible.

```text
Same dimension       → compatible
One dimension is 1   → compatible
Different dimensions → incompatible
```

---

## Example: Same Shape

```python
a.shape = (2, 3)
b.shape = (2, 3)
```

Compare:

```text
(2, 3)
(2, 3)
 ↑  ↑
```

Both dimensions are equal, so broadcasting is possible.

```python
a + b
```

works normally.

> **Note:**  
> This is not really a special broadcasting case because both arrays already have the same shape. The operation can simply be performed element by element.

---

## Example: Dimension of 1

```python
a.shape = (2, 3)
b.shape = (1, 3)
```

Compare from the right:

```text
(2, 3)
(1, 3)
 ↑  ↑
```

```text
3 vs 3 → equal       → compatible
2 vs 1 → one is 1   → compatible
```

Therefore, broadcasting is possible.

Conceptually:

```text
a:          [1 2 3]
            [4 5 6]

b:          [10 20 30]
            [10 20 30]   ← broadcast
```

So:

```python
a + b
```

produces:

```text
[11 22 33]
[14 25 36]
```

---

## Example: 1-D Array Broadcasting

```python
a.shape = (2, 3)
b.shape = (3,)
```

The dimensions are aligned **from the right**:

```text
(2, 3)
(   3)
```

The `3` matches:

```text
3 vs 3 → compatible
```

The missing dimension can be treated conceptually as `1`:

```text
(2, 3)
(1, 3)
```

Now:

```text
2 vs 1 → compatible
3 vs 3 → compatible
```

Therefore, broadcasting is possible.

Example:

```python
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([10, 20, 30])

a + b
```

Conceptually:

```text
[1 2 3]       [10 20 30]
[4 5 6]   +   [10 20 30]
```

Output:

```text
[11 22 33]
[14 25 36]
```

---

## Row vs Column Broadcasting

This is an important distinction.

Suppose:

```python
a.shape = (3, 4)
```

### `(4,)` → Broadcast Across Columns

```python
b.shape = (4,)
```

Conceptually:

```text
a:              b:

[1  2  3  4]    [10 20 30 40]
[5  6  7  8]
[9 10 11 12]
```

The `(4,)` array is broadcast across all rows:

```text
[10 20 30 40]
[10 20 30 40]
[10 20 30 40]
```

---

### `(3, 1)` → Broadcast Across Rows

```python
b.shape = (3, 1)
```

Conceptually:

```text
a:              b:

[1  2  3  4]    [10]
[5  6  7  8]    [20]
[9 10 11 12]    [30]
```

The values are broadcast horizontally:

```text
[10 10 10 10]
[20 20 20 20]
[30 30 30 30]
```

> **Remember:**  
> `(4,)` and `(3,1)` broadcast in **different directions**.

---

## `(3,)` vs `(3,1)`

These are **not the same shape**.

```python
a = np.array([1, 2, 3])
a.shape
# (3,)
```

This is a **1-D array**.

Whereas:

```python
b = np.array([[1],
              [2],
              [3]])

b.shape
# (3, 1)
```

This is a **2-D array**.

Even though they contain the same values, their shapes and broadcasting behavior are different.

---

## Broadcasting with More Than Two Dimensions

Broadcasting also works with higher-dimensional arrays.

For example:

```text
A.shape = (2, 3, 4)
B.shape = (3, 4)
```

Align the dimensions from the right:

```text
(2, 3, 4)
(   3, 4)
```

Compare:

```text
4 vs 4 → equal       → compatible
3 vs 3 → equal       → compatible
2 vs nothing →       → compatible
```

Therefore, broadcasting is possible.

> **Remember:**  
> The same right-to-left rule applies regardless of how many dimensions the arrays have.

---

## When Broadcasting Fails

Consider:

```python
a.shape = (2, 3)
b.shape = (2, 2)
```

Compare from the right:

```text
(2, 3)
(2, 2)
```

The rightmost dimensions are:

```text
3 vs 2
```

They are different, and neither is `1`.

Therefore:

```text
❌ Broadcasting is not possible.
```

NumPy will raise a broadcasting-related error when you try to perform the operation.

---

## Broadcasting with Arithmetic Operations

Broadcasting can be used with many element-wise arithmetic operations:

```python
a + b
a - b
a * b
a / b
a ** b
```

For example:

```python
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([10, 20, 30])

a * b
```

Conceptually:

```text
[1 2 3]       [10 20 30]
[4 5 6]   ×   [10 20 30]
```

Output:

```text
[10  40  90]
[40 100 180]
```

---

## Broadcasting with NumPy Functions

Broadcasting is not limited to arithmetic operators.

It can also occur when using NumPy functions and operations involving arrays of compatible shapes.

For example:

```python
np.sqrt(arr)
np.sin(arr)
np.exp(arr)
```

These functions operate element by element on the array.

Broadcasting becomes particularly useful when a function or operation involves arrays with different but compatible shapes.

---

## Broadcasting with Comparisons

Broadcasting also works with comparison operations.

Example:

```python
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

arr > np.array([2, 2, 2])
```

The `(3,)` array is broadcast across the rows.

Conceptually:

```text
arr:             comparison:

[1 2 3]          [2 2 2]
[4 5 6]          [2 2 2]
```

The comparison is performed element by element:

```text
[[False, False, True],
 [ True,  True, True]]
```

> **Remember:**  
> Broadcasting can be used with **comparisons**, not just arithmetic operations.

---

## Broadcasting Does Not Necessarily Copy the Smaller Array

When we say:

> "The smaller array is broadcast to the size of the larger array"

this describes the **effect** of broadcasting.

It does not necessarily mean NumPy physically creates multiple copies of the smaller array.

For example:

```python
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([10, 20, 30])

a + b
```

We can **conceptually** think of `b` as:

```text
[10 20 30]
[10 20 30]
```

but NumPy can perform the operation efficiently without actually creating that repeated array in memory.

---

## `np.broadcast_to()`

NumPy provides `np.broadcast_to()` to explicitly view an array as having a larger broadcasted shape.

Example:

```python
a = np.array([10, 20, 30])

np.broadcast_to(a, (2, 3))
```

Conceptually gives:

```text
[[10 20 30]
 [10 20 30]]
```

> **Remember:**  
> You normally do **not** need `np.broadcast_to()` for ordinary operations. NumPy automatically handles broadcasting when the shapes are compatible.

---

## The Most Important Rule

When checking whether two arrays can be broadcast:

### Always start from the **rightmost dimension**.

For every pair of dimensions:

```text
Same             → ✅ Compatible
One is 1         → ✅ Compatible
Different, neither is 1 → ❌ Incompatible
```

Example:

```text
(4, 3, 2)
(   3, 1)
```

Align from the right:

```text
(4, 3, 2)
(   3, 1)
```

Compare:

```text
2 vs 1 → ✅
3 vs 3 → ✅
4 vs nothing → ✅
```

Therefore, broadcasting is possible.

---

## Quick Mental Model

Think of broadcasting as:

```text
Different shapes
      ↓
Align from the RIGHT
      ↓
Compare dimensions
      ↓
Are they equal?
   ↙       ↘
 YES        NO
  ↓          ↓
  ✅     Is one of them 1?
             ↙    ↘
           YES     NO
            ↓       ↓
           ✅       ❌
```

> **PRO-TIP:**  
> Before performing an operation between two NumPy arrays, check their `.shape` values. If the shapes are different, mentally align them from the **right** and apply the broadcasting rules.

---