
**NOTE**-
>`Proper notes on broadcasting is given in the next file.`

In [2]:
import numpy as np

In [3]:
arr1 = np.arange(1,21).reshape(4,5)
arr2 = np.ones(20,dtype=np.int8).reshape(4,5)
print(arr1)
print()
print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [4]:
arr1 + arr2     # same shape. No need for broadcasting.

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21]])

In [5]:
arr1 + 10       # different shapes. Compatible for broadcasting.

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [6]:
# arr3 = np.ones(20,dtype=np.int8).reshape(5,4)
# arr2 + arr3  # different shapes. Not compatible to broadcast.
#             # ValueError: operands could not be broadcast together with shapes (4,5) (5,4).

In [7]:
arr4 = np.arange(1,6)
print(arr4)
print()
print(arr2)
arr2 + arr4         # arr4 is broadcast to (4,5).

[1 2 3 4 5]

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


array([[2, 3, 4, 5, 6],
       [2, 3, 4, 5, 6],
       [2, 3, 4, 5, 6],
       [2, 3, 4, 5, 6]])

In [8]:
arr5 = np.arange(1,7).reshape(3,2)
arr6 = np.linspace(10,60,6,dtype=int).reshape(3,2)
print(arr5)
print()
print(arr6)
arr5 + arr6

[[1 2]
 [3 4]
 [5 6]]

[[10 20]
 [30 40]
 [50 60]]


array([[11, 22],
       [33, 44],
       [55, 66]])

In [9]:
# arr6 = arr6.reshape(2,3)  
# arr5 + arr6           # shapes (3,2) and (2,3) can not be broadcast together.


In [10]:
arr7 = np.array([[1,2]])  
print(arr7.shape)
arr5 + arr7             # (3,2) and (1,2) do broadcast together.

(1, 2)


array([[2, 4],
       [4, 6],
       [6, 8]])

In [11]:
arr9 = np.array([[1,2,3]])
arr10 = arr9.reshape(3,1)
print(arr9)
print()
print(arr10)
print()
print(arr9.shape)
print()
print(arr10.shape) 
arr9 * arr10        # both arrays are broadcast to (3,3).

[[1 2 3]]

[[1]
 [2]
 [3]]

(1, 3)

(3, 1)


array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [12]:
print(arr1)
arr8 = arr1[1]
print(arr8)
arr1 > arr8         # broadcasting with comparision.


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[ 6  7  8  9 10]


array([[False, False, False, False, False],
       [False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [13]:
~((arr1 > arr8))

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [False, False, False, False, False],
       [False, False, False, False, False]])