In [ ]:
import numpy as np

In [ ]:
np.random.random() # returns a random value in [0,1).

0.5204517860512421

In [ ]:
np.random.randint(1,100) # returns a random value in [1,100).

45

In [ ]:
np.random.randint(1, 10, size=(2, 3)) # returns array of shape(2,3) initialized by random ints between [1,10).

array([[3, 4, 6],
       [3, 9, 8]], dtype=int32)

In [ ]:
np.random.uniform(1, 10) # returns a floating-point number in [1,10)

9.714354181474578

In [ ]:
np.random.uniform(1, 10, size=(2, 3)) # returns array of shape(2,3) initialized by random floats between [1,10).

array([[1.03948532, 9.99384943, 6.10712523],
       [2.64007929, 4.25410637, 2.44454342]])

In [ ]:
print(np.random.uniform(1,10, size=(4, 3)) ) # Generates random floats directly in a (4,3) array.
print()
print(np.random.uniform(1,10,12).reshape(4, 3)) 
                                    # Generates 12 random floats first, then reshapes them into (4,3) array.

[[5.13892239 5.91712134 8.18743232]
 [3.57146967 5.4122817  6.39199277]
 [1.13979948 6.34133267 4.90308714]
 [8.26624476 3.83720323 9.03599838]]

[[6.20071494 2.65609181 8.0913631 ]
 [6.50828059 1.48518345 4.78174312]
 [7.11161953 9.267416   1.00361822]
 [9.79083234 4.38922283 9.76405185]]


In [ ]:
np.random.seed(1)  # Sets the seed so the same sequence of random numbers is generated each time.
np.random.random()

0.417022004702574

In [ ]:
print(np.random.random())  # every re-run prints different values.
print(np.random.random())
print(np.random.random())

0.6704675101784022
0.41730480236712697
0.5586898284457517


In [ ]:
np.random.seed(1)  # Sets the seed so the same sequence of random numbers is generated each time.
print(np.random.random())
print(np.random.random())
print(np.random.random())

0.417022004702574
0.7203244934421581
0.00011437481734488664


---

## `np.random.seed()`

```python
np.random.seed(1)
```

Sets the **starting state of the random number generator**.

Using the same seed produces the **same sequence of random numbers** each time.

> **Remember:**  
> `seed()` does not fix one random number; it makes the **entire sequence reproducible**.

### Choosing a Seed

The seed can be any **non-negative integer**:

```python
np.random.seed(0)      # valid
np.random.seed(1)      # valid
np.random.seed(1000)   # valid
```

Different seeds generally produce different sequences:

```text
seed(0)    → Sequence A
seed(1)    → Sequence B
seed(42)   → Sequence C
```

But using the **same seed** again reproduces the same sequence.

```python
np.random.seed(1000)
```

Running the same code again with `seed(1000)` produces the same sequence of random numbers.

### Negative Seeds

Negative integers are **not valid** for `np.random.seed()`:

```python
np.random.seed(-1)     # ❌
```

So:

```text
0 or positive integer → ✅
negative integer      → ❌
```

---

In [ ]:
arr1 = np.random.randint(1,100,10)
print(arr1)
np.max(arr1) # returns the max element of arr1.

[92 50  1 23 98 71 37 19 28 29]
98


np.int32(98)

In [ ]:
arr1 = np.random.randint(1,100,10)
print(arr1)
print(np.max(arr1))      # prints the max value/element in arr1.
print(np.argmax(arr1))   # prints index of max element in arr1.

[13 18 34 11 29 76  6 82  6 43]
82
7


In [ ]:
arr1 = np.random.randint(1,100,10)
print(arr1)
print(np.min(arr1))
print(np.argmin(arr1))

[34 28 52 78 31 44 47 10 68  4]
4
9


np.int64(0)

In [ ]:
print(np.min(2))         # treats 2 as array element with index 0.
print(np.argmin(2))

2
0


In [ ]:
np.random.seed(10)          # seeding to 10.
arr2 = np.random.randint(0,100,20)
print(arr2)
arr2[arr2%2 != 0] = -1      # Replaces all odd elements in arr2 with -1.
                            # This changes the original array (in-place).
print(arr2)


[ 9 15 64 28 89 93 29  8 73  0 40 36 16 11 54 88 62 33 72 78]
[-1 -1 64 28 -1 -1 -1  8 -1  0 40 36 16 -1 54 88 62 -1 72 78]


In [ ]:
np.random.seed(10)      # seeding to 10.
arr2 = np.random.randint(0,100,20)
print(arr2)
print()
print(np.where(arr2%2 != 0,-1,arr2))    # Returns new array with all odd ints replaced by -1.
print()                                 # Does not modify the original array.
print(arr2)


[ 9 15 64 28 89 93 29  8 73  0 40 36 16 11 54 88 62 33 72 78]

[-1 -1 64 28 -1 -1 -1  8 -1  0 40 36 16 -1 54 88 62 -1 72 78]

[ 9 15 64 28 89 93 29  8 73  0 40 36 16 11 54 88 62 33 72 78]


In [ ]:
arr3 = np.array([5, 8, 3, 10])
np.where(arr3 > 5)  # Returns a tuple of the array of indices of all the elements in arr for which condition is true.
                    # NOTE - The above statement returns a tuple of arrays.

(array([1, 3]),)

In [ ]:
arr3 = np.array([5, 8, 3, 10])
np.where(arr3 > 5)[0] # returns the first index array.

array([1, 3])

In [ ]:
arr3 = np.array([5, 8, 3, 10, 20, 32, 13, 31, 4]).reshape(3,3)
print(arr3)
print()
print(np.where(arr3 > 5))        # Returns a tuple with 2 arrays:
                                    # The first array contains row indices.
                                    # Second array contains column indices.
print()
print(np.where(arr3>5)[0])      # Returns the first index array only. (row index only).
print(np.where(arr3>5)[1])      # Returns the second index array only. (col index only).

[[ 5  8  3]
 [10 20 32]
 [13 31  4]]

(array([0, 1, 1, 1, 2, 2]), array([1, 0, 1, 2, 0, 1]))

[0 1 1 1 2 2]
[1 0 1 2 0 1]


---

## Why `np.where(condition)` Returns a Tuple

When `np.where()` is used with **only a condition**:

```python
np.where(condition)
```

it returns a **tuple containing arrays of indices**, rather than an array directly.

For a 1-D array:

```python
arr = np.array([5, 8, 3, 10])

np.where(arr > 5)
```

returns:

```python
(array([1, 3]),)
```

The comma is important:

```python
(array([1, 3]),)
```

means **a tuple containing one array**.

### Why a Tuple?

`np.where()` also works with multidimensional arrays.

For example:

```python
arr = np.array([[5, 8, 3],
                [10, 2, 7]])

np.where(arr > 5)
```

returns:

```python
(array([0, 1, 1]), array([1, 0, 2]))
```

- First array → row indices
- Second array → column indices

Together, they identify the positions where the condition is `True`:

```text
(0, 1) → 8
(1, 0) → 10
(1, 2) → 7
```

> **Remember:**  
> The number of index arrays returned by `np.where(condition)` corresponds to the **number of dimensions** of the input array.

For a 1-D array → one index array:

```python
(array([1, 3]),)
```

For a 2-D array → two index arrays:

```python
(array([0, 1, 1]), array([1, 0, 2]))
```

To extract the index array from a 1-D result:

```python
np.where(arr > 5)[0]
```

returns:

```python
array([1, 3])
```

---


In [ ]:
arr4 = np.array([5, 8, 3, 10, 20, 32, 13, 31, 4]).reshape(3,3)
print(arr4)
np.where(arr4%2 != 0, -1,1)  # Returns a new array with all odd ints replaced by -1 and even ints by 1.

[[ 5  8  3]
 [10 20 32]
 [13 31  4]]


array([[-1,  1, -1],
       [ 1,  1,  1],
       [-1, -1,  1]])

**NOTE-**
>`np.where()` generally preserves the shape of its input/condition (after broadcasting).

In [ ]:
arr5 = np.arange(-10,11)
print(arr5)
print(np.where(arr5>=0,arr5,-arr5)) # returns an array whose elements are absolute values of all elements.
print(np.abs(arr5))

[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4   5   6   7
   8   9  10]
[10  9  8  7  6  5  4  3  2  1  0  1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1  0  1  2  3  4  5  6  7  8  9 10]


---

## `np.where(condition, x, y)`

The 3-argument form of `np.where()` works like an **element-by-element if-else**.

```python
np.where(condition, x, y)
```

- `condition` → condition to check for each element.
- `x` → value selected when the condition is `True`.
- `y` → value selected when the condition is `False`.

Example:

```python
arr = np.array([5, 8, 3, 10])

np.where(arr > 5, -1, arr)
```

Output:

```text
[ 5 -1  3 -1]
```

Conceptually:

```text
arr > 5
   ↓
5  → False → use arr value →  5
8  → True  → use -1         → -1
3  → False → use arr value →  3
10 → True  → use -1         → -1
```

So:

```python
np.where(condition, x, y)
```

can be thought of as:

```text
if condition is True  → x
if condition is False → y
```

> **Remember:**  
> The operation is performed **element by element** and `np.where()` returns a **new array**; it does not modify the original array in-place.

---