# Reading & Writing Files

NumPy provides several functions for **reading data from files and writing arrays to files**. These are especially useful when numerical data is stored in text files, CSV files, or NumPy's own binary formats.

---

## Reading Text Files

### `np.loadtxt()`

Reads numerical data from a **clean and consistently formatted text file**.

### Syntax

```python
np.loadtxt(
    fname,
    dtype=float,
    comments='#',
    delimiter=None,
    converters=None,
    skiprows=0,
    usecols=None,
    unpack=False,
    ndmin=0
)
```

### Example

Suppose `data.txt` contains:

```text
1,2,3
4,5,6
7,8,9
```

```python
arr = np.loadtxt('data.txt', delimiter=',')

print(arr)
```

Output:

```text
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
```

### Important arguments

| Argument | Purpose |
|---|---|
| `fname` | File name or path |
| `dtype` | Data type of the resulting array |
| `delimiter` | Character separating values |
| `comments` | Character marking the beginning of comments |
| `skiprows` | Number of rows to skip from the beginning |
| `usecols` | Columns to read |
| `unpack` | If `True`, transpose the resulting array |
| `converters` | Functions used to convert values while reading |
| `ndmin` | Minimum number of dimensions of the result |

### `dtype`

Specifies the data type.

```python
arr = np.loadtxt('data.txt', delimiter=',', dtype=int)

print(arr.dtype)
```

Output:

```text
int64
```

### `delimiter`

Specifies the character separating values.

```python
arr = np.loadtxt('data.txt', delimiter=',')
```

For whitespace-separated data, the delimiter can be omitted.

### `skiprows`

Skips rows from the beginning of the file.

```text
# Data
1,2,3
4,5,6
```

```python
arr = np.loadtxt(
    'data.txt',
    delimiter=',',
    skiprows=1
)
```

The comment/header row is skipped.

### `usecols`

Reads only selected columns.

```python
arr = np.loadtxt(
    'data.txt',
    delimiter=',',
    usecols=(0, 2)
)

print(arr)
```

Output:

```text
[[1. 3.]
 [4. 6.]
 [7. 9.]]
```

Column indexing starts at `0`.

### `unpack`

If `False` (default), the data keeps its normal orientation.

If `True`, the resulting array is transposed.

```python
x, y = np.loadtxt(
    'data.txt',
    unpack=True
)
```

This is useful when you want to assign columns directly to separate variables.

---

## `np.genfromtxt()`

`np.genfromtxt()` is similar to `loadtxt()` but is **more flexible** and can handle missing or irregular data.

### Syntax

```python
np.genfromtxt(
    fname,
    dtype=float,
    comments='#',
    delimiter=None,
    skip_header=0,
    skip_footer=0,
    converters=None,
    missing_values=None,
    filling_values=None,
    usecols=None,
    unpack=False,
    ndmin=0
)
```

### Example

Suppose the file contains:

```text
1,2,3
4,,6
,8,9
```

```python
arr = np.genfromtxt(
    'data.txt',
    delimiter=',',
    filling_values=np.nan
)

print(arr)
```

Output:

```text
[[ 1.  2.  3.]
 [ 4. nan  6.]
 [nan  8.  9.]]
```

### Important arguments

| Argument | Purpose |
|---|---|
| `fname` | File name or path |
| `dtype` | Data type of the resulting array |
| `delimiter` | Character separating values |
| `skip_header` | Number of rows to skip at the beginning |
| `skip_footer` | Number of rows to skip at the end |
| `usecols` | Columns to read |
| `unpack` | If `True`, transpose the result |
| `converters` | Functions used to convert values |
| `missing_values` | Values that should be treated as missing |
| `filling_values` | Values used to replace missing data |

### `missing_values`

Specifies values that should be considered missing.

```python
arr = np.genfromtxt(
    'data.txt',
    delimiter=',',
    missing_values=''
)
```

### `filling_values`

Specifies what should replace missing values.

```python
arr = np.genfromtxt(
    'data.txt',
    delimiter=',',
    missing_values='',
    filling_values=np.nan
)
```

For:

```text
1,2,3
4,,6
```

the missing value becomes `nan`.

### `skip_header`

Skips rows from the beginning.

```python
arr = np.genfromtxt(
    'data.txt',
    delimiter=',',
    skip_header=1
)
```

### `skip_footer`

Skips rows from the end.

```python
arr = np.genfromtxt(
    'data.txt',
    delimiter=',',
    skip_footer=1
)
```

### `converters`

Allows specific columns to be processed by a function while reading.

```python
arr = np.genfromtxt(
    'data.txt',
    converters={0: lambda x: float(x) * 2}
)
```

Here, values in column `0` are multiplied by `2` while being read.

> **Key difference:**
>
> `np.loadtxt()` → best for **clean numerical data**  
> `np.genfromtxt()` → more flexible and useful for **missing or irregular data**

---

# Writing Text Files

### `np.savetxt()`

Writes a NumPy array to a **text file**.

### Syntax

```python
np.savetxt(
    fname,
    X,
    fmt='%.18e',
    delimiter=' ',
    newline='\n',
    header='',
    footer='',
    comments='# '
)
```

### Example

```python
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

np.savetxt(
    'data.txt',
    arr,
    fmt='%d'
)
```

The resulting `data.txt` contains:

```text
1 2 3
4 5 6
```

### `fmt`

Controls the format in which values are written.

```python
np.savetxt('data.txt', arr, fmt='%.2f')
```

For:

```text
[[1.23456 2.34567]]
```

the file contains approximately:

```text
1.23 2.35
```

### `delimiter`

Specifies the separator.

```python
np.savetxt(
    'data.csv',
    arr,
    delimiter=',',
    fmt='%d'
)
```

The resulting file contains:

```text
1,2,3
4,5,6
```

### `header`

Adds a header to the file.

```python
np.savetxt(
    'data.txt',
    arr,
    fmt='%d',
    header='A B C'
)
```

The header is written at the beginning of the file.

---

# NumPy Binary Files

Text files are convenient for human-readable data, but NumPy also provides binary formats that preserve NumPy-specific information such as `dtype` and shape.

## `np.save()`

Saves a single NumPy array in NumPy's binary `.npy` format.

```python
arr = np.array([1, 2, 3])

np.save('data.npy', arr)
```

The file can later be loaded with:

```python
arr2 = np.load('data.npy')

print(arr2)
```

Output:

```text
[1 2 3]
```

> **Key idea:** `.npy` is designed specifically for storing a **single NumPy array** efficiently while preserving its NumPy information.

---

## `np.savez()`

Stores **multiple arrays** in a single `.npz` file.

```python
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.savez('data.npz', first=a, second=b)
```

Load them with:

```python
data = np.load('data.npz')

print(data['first'])
print(data['second'])
```

Output:

```text
[1 2 3]
[4 5 6]
```

---

## `np.savez_compressed()`

Same basic idea as `np.savez()`, but stores the arrays using **compression**, which can reduce file size.

```python
np.savez_compressed(
    'data.npz',
    first=a,
    second=b
)
```

Load it in the same way:

```python
data = np.load('data.npz')

print(data['first'])
```

---

# Quick Comparison

| Function | Purpose | Format |
|---|---|---|
| `np.loadtxt()` | Read clean numerical text data | Text |
| `np.genfromtxt()` | Read text data with missing/irregular values | Text |
| `np.savetxt()` | Write arrays to text files | Text |
| `np.save()` | Save one NumPy array | `.npy` |
| `np.load()` | Load `.npy` or `.npz` files | Binary |
| `np.savez()` | Save multiple arrays | `.npz` |
| `np.savez_compressed()` | Save multiple compressed arrays | `.npz` |

> **Remember:**
>
> **Text files**
>
> ```text
> loadtxt()       → read
> genfromtxt()    → read with more flexibility
> savetxt()       → write
> ```
>
> **NumPy binary files**
>
> ```text
> save()              → save one array
> load()              → load saved arrays
> savez()             → save multiple arrays
> savez_compressed()  → save multiple arrays with compression
> ```
>
> Use **text formats** when human readability and interoperability are important. Use **`.npy` / `.npz`** when you primarily want to store and restore NumPy arrays while preserving their NumPy-specific information.