# Array Manipulation & Reshaping

These operations change the **shape, dimensions, or arrangement** of an array. They are useful when the data has the right values but needs to be organized differently.

### `reshape()`

Changes the shape of an array without changing its elements.

```python
arr = np.arange(6)

print(arr.reshape(2, 3))
```

Output:

```text
[[0 1 2]
 [3 4 5]]
```

### `ravel()`

Returns a flattened **1-D view when possible**.

```python
arr = np.array([[1, 2], [3, 4]])

print(arr.ravel())
```

Output:

```text
[1 2 3 4]
```

### `flatten()`

Returns a **flattened copy** of the array.

```python
arr = np.array([[1, 2], [3, 4]])

print(arr.flatten())
```

Output:

```text
[1 2 3 4]
```

### `transpose()` / `.T`

Reverses the axes of a 2-D array, effectively swapping rows and columns.

```python
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(arr.T)
```

Output:

```text
[[1 4]
 [2 5]
 [3 6]]
```

### `np.tile()`

Repeats an array a specified number of times.

```python
arr = np.array([1, 2, 3])

print(np.tile(arr, 2))
```

Output:

```text
[1 2 3 1 2 3]
```

### `np.unravel_index()`

Converts a **flat index** into the corresponding multidimensional index.

```python
arr = np.arange(6).reshape(2, 3)

print(np.unravel_index(4, arr.shape))
```

Output:

```text
(1, 1)
```

Because:

```text
arr[1, 1] = 4
```

> **Key idea:** These functions mainly change **how array elements are organized or accessed**, rather than changing the values themselves.

# Combining & Splitting Arrays

These functions are used to **join arrays together or divide an array into smaller arrays**. The `axis` parameter determines the direction of the operation.

### `np.append()`

Appends values to an array. It returns a **new array** and does not modify the original array.

```python
arr = np.array([1, 2, 3])

print(np.append(arr, [4, 5]))
```

Output:

```text
[1 2 3 4 5]
```

### `np.concatenate()`

Joins arrays along an **existing axis**.

```python
a = np.array([1, 2])
b = np.array([3, 4])

print(np.concatenate((a, b)))
```

Output:

```text
[1 2 3 4]
```

### `np.vstack()`

Stacks arrays **vertically**, adding rows.

```python
a = np.array([1, 2])
b = np.array([3, 4])

print(np.vstack((a, b)))
```

Output:

```text
[[1 2]
 [3 4]]
```

### `np.hstack()`

Stacks arrays **horizontally**.

```python
a = np.array([1, 2])
b = np.array([3, 4])

print(np.hstack((a, b)))
```

Output:

```text
[1 2 3 4]
```

### `np.split()`

Splits an array into multiple sub-arrays at specified positions.

```python
arr = np.arange(6)

print(np.split(arr, 3))
```

Output:

```text
[array([0, 1]), array([2, 3]), array([4, 5])]
```

### `np.vsplit()`

Splits an array **vertically**, along the rows.

```python
arr = np.arange(8).reshape(4, 2)

print(np.vsplit(arr, 2))
```

Output:

```text
[array([[0, 1],
        [2, 3]]),
 array([[4, 5],
        [6, 7]])]
```

### `np.hsplit()`

Splits an array **horizontally**, along the columns.

```python
arr = np.arange(8).reshape(2, 4)

print(np.hsplit(arr, 2))
```

Output:

```text
[array([[0, 1],
        [4, 5]]),
 array([[2, 3],
        [6, 7]])]
```

> **Key idea:** When combining arrays, their dimensions must be compatible along the axes that are not being joined.

# Iterating Over Arrays

Iteration means going through the elements of an iterable one by one. Python provides the built-in `enumerate()` function for iterating while keeping track of the index. NumPy provides `np.ndenumerate()` and `np.ndindex()` for working conveniently with **multidimensional array indices**.

## Python's `enumerate()`

Python's built-in `enumerate()` returns both the **index and value** while iterating over an iterable.

```python
arr = [10, 20, 30]

for index, value in enumerate(arr):
    print(index, value)
```

Output:

```text
0 10
1 20
2 30
```

It is essentially a convenient way to obtain:

```text
index + value
```

---

## `np.ndenumerate()`

`np.ndenumerate()` is similar to Python's `enumerate()`, but is designed for **NumPy arrays of any number of dimensions**.

It returns the **index tuple and corresponding value** for every element.

```python
arr = np.array([[10, 20],
                [30, 40]])

for index, value in np.ndenumerate(arr):
    print(index, value)
```

Output:

```text
(0, 0) 10
(0, 1) 20
(1, 0) 30
(1, 1) 40
```

The index is a tuple containing one coordinate for each dimension:

```text
(0, 1)
 ↓  ↓
row column
```

For a 1-D array:

```python
arr = np.array([10, 20, 30])

for index, value in np.ndenumerate(arr):
    print(index, value)
```

Output:

```text
(0,) 10
(1,) 20
(2,) 30
```

> **Key idea:** `np.ndenumerate()` → **multidimensional index + value**.

---

## `np.ndindex()`

`np.ndindex()` generates **all valid index tuples** for a given shape.

It takes the **shape**, rather than the array itself, because it only needs to generate indices and does not need the array's values.

```python
arr = np.arange(6).reshape(2, 3)

for index in np.ndindex(arr.shape):
    print(index)
```

Output:

```text
(0, 0)
(0, 1)
(0, 2)
(1, 0)
(1, 1)
(1, 2)
```

Since:

```python
arr.shape
```

is:

```text
(2, 3)
```

`np.ndindex()` generates every valid combination of row and column indices.

To access the corresponding values:

```python
for index in np.ndindex(arr.shape):
    print(index, arr[index])
```

Output:

```text
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
```

Here, `np.ndindex()` gives only the index, and `arr[index]` is used separately to obtain the value.

---

## Quick Comparison

| Tool | Input | Produces |
|---|---|---|
| `enumerate()` | Iterable | Index + value |
| `np.ndenumerate()` | NumPy array | Multidimensional index + value |
| `np.ndindex()` | Array shape | Multidimensional indices |

### Remember

```text
enumerate()
    ↓
index + value

np.ndenumerate()
    ↓
multidimensional index + value

np.ndindex(arr.shape)
    ↓
multidimensional indices
    ↓
arr[index] → value
```

> **Key difference:** Use `np.ndenumerate()` when you want the **indices and values together**. Use `np.ndindex()` when you primarily need to **iterate over all valid indices**.

# Sorting & Searching

These functions help **order array elements, find their positions, or locate particular values**.

### `np.sort()`

Returns a **sorted copy** of an array. The original array is unchanged.

```python
arr = np.array([3, 1, 2])

print(np.sort(arr))
print(arr)
```

Output:

```text
[1 2 3]
[3 1 2]
```

### `ndarray.sort()`

Sorts the array **in-place**, modifying the original array.

```python
arr = np.array([3, 1, 2])

arr.sort()
print(arr)
```

Output:

```text
[1 2 3]
```

### `np.argsort()`

Returns the **indices that would sort the array**.

```python
arr = np.array([30, 10, 20])

print(np.argsort(arr))
```

Output:

```text
[1 2 0]
```

These indices give the sorted order:

```text
arr[1] → 10
arr[2] → 20
arr[0] → 30
```

### `np.argmin()`

Returns the **index of the smallest element**.

```python
arr = np.array([30, 10, 20])

print(np.argmin(arr))
```

Output:

```text
1
```

### `np.argmax()`

Returns the **index of the largest element**.

```python
arr = np.array([30, 10, 20])

print(np.argmax(arr))
```

Output:

```text
0
```

### Finding the Closest Value

A useful pattern is:

```python
arr = np.array([1, 5, 8, 12, 20])
x = 10

print(arr[np.abs(arr - x).argmin()])
```

Output:

```text
8
```

`np.abs(arr - x)` calculates the distance of every element from `x`, and `argmin()` finds the index of the smallest distance.

> **Key idea:**
>
> - `sort()` → sorted **values**
> - `argsort()` → sorting **indices**
> - `argmin()` → index of **minimum**
> - `argmax()` → index of **maximum**

# Universal Functions (ufuncs)

A **ufunc (universal function)** performs an operation element-by-element on NumPy arrays.

Examples include:

```python
np.add()
np.subtract()
np.multiply()
np.divide()
np.maximum()
np.minimum()
```

### `np.add()`

Adds corresponding elements.

```python
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.add(a, b))
```

Output:

```text
[5 7 9]
```

### `np.subtract()`

Subtracts corresponding elements.

```python
print(np.subtract([5, 6, 7], [1, 2, 3]))
```

Output:

```text
[4 4 4]
```

### `np.multiply()`

Multiplies corresponding elements.

```python
print(np.multiply([1, 2, 3], [4, 5, 6]))
```

Output:

```text
[ 4 10 18]
```

### `np.divide()`

Divides corresponding elements.

```python
print(np.divide([10, 20, 30], [2, 4, 5]))
```

Output:

```text
[5. 5. 6.]
```

### `np.maximum()`

Selects the larger value from each pair of corresponding elements.

```python
print(np.maximum([1, 5, 3], [2, 4, 6]))
```

Output:

```text
[2 5 6]
```

### `np.minimum()`

Selects the smaller value from each pair.

```python
print(np.minimum([1, 5, 3], [2, 4, 6]))
```

Output:

```text
[1 4 3]
```

> **Key idea:** Ufuncs allow mathematical and comparison operations to be performed **element-wise on entire arrays** without explicitly writing a Python loop.

# Mathematical & Numerical Operations

These functions perform mathematical operations such as **rounding values, manipulating signs, and calculating square roots**.

### `np.floor()`

Rounds values toward **negative infinity**.

```python
arr = np.array([1.7, -1.7])

print(np.floor(arr))
```

Output:

```text
[ 1. -2.]
```

### `np.ceil()`

Rounds values toward **positive infinity**.

```python
arr = np.array([1.2, -1.2])

print(np.ceil(arr))
```

Output:

```text
[ 2. -1.]
```

### `np.trunc()`

Removes the fractional part by rounding **toward zero**.

```python
arr = np.array([1.7, -1.7])

print(np.trunc(arr))
```

Output:

```text
[ 1. -1.]
```

### `np.sign()`

Returns the sign of each value:

```text
negative → -1
zero     →  0
positive →  1
```

```python
arr = np.array([-5, 0, 7])

print(np.sign(arr))
```

Output:

```text
[-1  0  1]
```

### `np.copysign()`

Returns the magnitude of the first argument with the **sign of the second argument**.

```python
print(np.copysign([2, 3, 4], [-1, 1, -1]))
```

Output:

```text
[-2.  3. -4.]
```

### `np.sqrt()`

Calculates the square root of each element.

```python
print(np.sqrt([1, 4, 9]))
```

Output:

```text
[1. 2. 3.]
```

For a negative real number, `np.sqrt()` returns `nan`:

```python
print(np.sqrt(-1))
```

Output:

```text
nan
```

### `np.emath.sqrt()`

Can handle negative inputs by returning a **complex result**.

```python
print(np.emath.sqrt(-1))
```

Output:

```text
1j
```

> **Key idea:** Pay attention to the difference between rounding toward **zero** (`trunc`) and rounding toward **negative/positive infinity** (`floor`/`ceil`).

# NumPy Set Operations

These functions perform common **set operations on 1-D arrays**. They generally work with unique values rather than preserving duplicate occurrences.

### `np.intersect1d()`

Returns the values that are **common to both arrays**.

```python
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])

print(np.intersect1d(a, b))
```

Output:

```text
[2 3]
```

### `np.union1d()`

Returns all **unique values present in either array**.

```python
print(np.union1d(a, b))
```

Output:

```text
[1 2 3 4]
```

### `np.setdiff1d()`

Returns values that are in the **first array but not the second**.

```python
print(np.setdiff1d(a, b))
```

Output:

```text
[1]
```

### `np.setxor1d()`

Returns values that appear in **exactly one** of the two arrays.

```python
print(np.setxor1d(a, b))
```

Output:

```text
[1 4]
```

> **Key idea:** These functions treat arrays as **sets of unique values**, so duplicate occurrences are not preserved.

# Array Comparison

NumPy provides different functions depending on whether you want to compare **individual elements, entire arrays, or approximate numerical values**.

### `np.equal()`

Performs an **element-wise exact comparison** and returns a Boolean array.

```python
a = np.array([1, 2, 3])
b = np.array([1, 5, 3])

print(np.equal(a, b))
```

Output:

```text
[ True False  True]
```

The `==` operator performs the same element-wise comparison:

```python
a == b
```

### `np.array_equal()`

Checks whether two arrays have the **same shape and exactly the same values**.

```python
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])

print(np.array_equal(a, b))
```

Output:

```text
True
```

Different shapes produce `False`:

```python
a = np.array([1, 2, 3])
b = np.array([[1, 2, 3]])

print(np.array_equal(a, b))
```

Output:

```text
False
```

### `np.allclose()`

Checks whether corresponding values are **close enough within a tolerance**. This is especially useful for floating-point calculations.

```python
a = np.array([1.0, 2.0, 3.0])
b = np.array([1.0, 2.000001, 3.0])

print(np.allclose(a, b))
```

Output:

```text
True
```

The values are not exactly equal, but their difference is small enough to be considered close.

> **Quick rule:**
>
> `np.equal()` → **Which elements are equal?**
>
> `np.array_equal()` → **Are these arrays exactly equal?**
>
> `np.allclose()` → **Are the corresponding values close enough?**

# Data Types & Numerical Limits

NumPy arrays have a **dtype** that determines how their elements are stored and interpreted. Different dtypes have different ranges, precision, and memory requirements.

### `dtype`

Specifies or describes the data type of an array.

```python
arr = np.array([1, 2, 3], dtype=np.float32)

print(arr.dtype)
```

Output:

```text
float32
```

### `astype()`

Converts an existing array to another dtype and returns a **new array**.

```python
arr = np.array([1.2, 2.8, 3.5])

print(arr.astype(int))
```

Output:

```text
[1 2 3]
```

Converting floats to integers **truncates** the fractional part; it does not round.

### Structured Arrays

A structured dtype allows each array element to contain **multiple named fields**.

```python
dtype = [
    ('position', [('x', float), ('y', float)]),
    ('color', [('r', float), ('g', float), ('b', float)])
]

arr = np.zeros(1, dtype=dtype)

print(arr)
```

Output:

```text
[((0., 0.), (0., 0., 0.))]
```

### `np.iinfo()`

Returns information about an **integer dtype**, including its minimum and maximum representable values.

```python
info = np.iinfo(np.int8)

print(info.min)
print(info.max)
```

Output:

```text
-128
127
```

### `np.finfo()`

Returns information about a **floating-point dtype**, including its precision and representable limits.

```python
info = np.finfo(np.float32)

print(info.eps)
print(info.max)
```

Output will contain values such as:

```text
1.1920929e-07
3.4028235e+38
```

`eps` is the difference between `1.0` and the next representable value.

> **Key idea:** `iinfo()` is for **integers**, while `finfo()` is for **floating-point numbers**.

# Date & Time

NumPy provides two main date/time types:

- `np.datetime64` → represents a **specific date or date/time**.
- `np.timedelta64` → represents a **duration or time interval**.

### `np.datetime64`

Creates a NumPy date/time value.

```python
today = np.datetime64('today')

print(today)
```

Output:

```text
2026-08-14
```

The exact output depends on the current date.

### `np.timedelta64`

Represents a time interval.

```python
one_day = np.timedelta64(1, 'D')

print(one_day)
```

Output:

```text
1 days
```

### Date Arithmetic

`datetime64` and `timedelta64` can be used together.

```python
today = np.datetime64('today')

print(today - np.timedelta64(1, 'D'))
print(today)
print(today + np.timedelta64(1, 'D'))
```

Output:

```text
2026-08-13
2026-08-14
2026-08-15
```

### Creating a Range of Dates

```python
arr = np.arange('2016-07', '2016-08', dtype='datetime64[D]')

print(arr)
```

This creates one `datetime64[D]` value for each day in July 2016.

> **Key idea:** `datetime64` represents **when**, while `timedelta64` represents **how much time**.

# Iteration & Array Construction

These tools are useful when creating arrays from **iterables** or iterating through existing arrays while accessing their indices.

### `np.fromiter()`

Creates a **1-D NumPy array from an iterable**.

```python
arr = np.fromiter((x * x for x in range(5)), dtype=int)

print(arr)
```

Output:

```text
[ 0  1  4  9 16]
```

The `dtype` argument is required.

### `np.ndenumerate()`

Iterates through an array while providing both the **index and value**.

```python
arr = np.array([[10, 20],
                [30, 40]])

for index, value in np.ndenumerate(arr):
    print(index, value)
```

Output:

```text
(0, 0) 10
(0, 1) 20
(1, 0) 30
(1, 1) 40
```

Unlike Python's `enumerate()`, `np.ndenumerate()` naturally handles multidimensional arrays and provides the complete index as a tuple.

> **Key idea:** `fromiter()` is mainly for **creating arrays from iterables**, while `ndenumerate()` is for **iterating through arrays with their indices**.

# Floating-Point Error Handling

NumPy provides tools for controlling how it responds to **floating-point errors** such as division by zero, overflow, underflow, and invalid operations.

### `np.seterr()`

Changes NumPy's **global floating-point error-handling settings**.

```python
np.seterr(divide='ignore')

print(np.array([1.0]) / 0)
```

Output:

```text
[inf]
```

The division-by-zero warning is suppressed.

### `np.geterr()`

Returns the current floating-point error-handling settings.

```python
print(np.geterr())
```

Typical output:

```text
{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}
```

The exact settings may differ depending on your environment.

### `np.errstate()`

Temporarily changes error-handling settings inside a `with` block.

```python
with np.errstate(divide='ignore'):
    print(np.array([1.0]) / 0)
```

Output:

```text
[inf]
```

Once the block ends, the previous settings are restored.

### Error Types

| Error | Meaning |
|---|---|
| `divide` | Division by zero |
| `over` | Floating-point overflow |
| `under` | Floating-point underflow |
| `invalid` | Invalid floating-point operation |

> **Key idea:** `np.seterr()` changes the settings globally, while `np.errstate()` is useful when you want the change to be **temporary**.

# Display & Printing

NumPy provides options for controlling **how arrays are represented when printed**. These settings affect the display of an array, not the actual data stored in it.

### `np.set_printoptions()`

Controls NumPy's array-printing behavior.

```python
np.set_printoptions(precision=2)

arr = np.array([1.23456, 7.89123])

print(arr)
```

Output:

```text
[1.23 7.89]
```

### `threshold`

Controls when NumPy starts **summarizing large arrays with `...`**.

```python
np.set_printoptions(threshold=float("inf"))

arr = np.arange(1, 20)

print(arr)
```

Output:

```text
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
```

Setting `threshold=float("inf")` tells NumPy not to summarize the array based on its number of elements.

> **Important:** This only controls NumPy's representation. A notebook or editor such as VS Code may still impose its own output limit and truncate what you see.