# NumPy

## What is NumPy?
- **NumPy** = **Numerical Python**.
- A Python library for **fast numerical computing**.
- Provides the **ndarray (N-dimensional array)** data structure.
- Faster and more memory-efficient than Python lists for numerical data.

## Why use NumPy?
- Fast mathematical operations.
- Less memory usage.
- Supports vectorized computations (no explicit loops needed).
- Foundation for libraries like **Pandas, SciPy, Matplotlib, Scikit-learn, TensorFlow, PyTorch**.

## Python List vs NumPy Array

### Python List
- Can store mixed data types.
- Slower for numerical computations.
- `list * 2` duplicates the list.

### NumPy Array
- Stores homogeneous (same type) elements.
- Faster and optimized in C.
- `array * 2` multiplies each element.

## ndarray
- Main data structure in NumPy.
- Can be:
  - 1D → Vector
  - 2D → Matrix
  - 3D+ → Higher-dimensional arrays

## Important Properties
- `shape` → Dimensions of the array.
- `ndim` → Number of dimensions.
- `size` → Total number of elements.
- `dtype` → Data type of elements.
- `itemsize` → Size (bytes) of one element.

## Common Array Creation Functions
- `np.array()` → Create from existing data.
- `np.zeros()` → Array of zeros.
- `np.ones()` → Array of ones.
- `np.full()` → Fill with a specified value.
- `np.empty()` → Uninitialized array.
- `np.arange()` → Array with a given step.
- `np.linspace()` → Evenly spaced values.
- `np.eye()` / `np.identity()` → Identity matrix.
- `np.diag()` → Create/extract diagonal.
- `np.random.randint()` → Random integers.

## Key Features
- Element-wise arithmetic (`+`, `-`, `*`, `/`)
- Broadcasting
- Indexing & slicing
- Reshaping
- Aggregation (`sum`, `mean`, `max`, `min`, etc.)
- Linear algebra operations


------------------------------------------------------------------------------





## `np.array()`

Creates a NumPy array from an **array-like object** (list, tuple, range, existing NumPy array, etc.).

### Function Signature

```python
np.array(
    object,      # Data to convert into an array (Required)
    dtype=None,  # Desired data type
    copy=True,   # Whether to copy the data
    order='K',   # Memory layout
    subok=False, # Preserve subclasses
    ndmin=0,     # Minimum number of dimensions
    like=None    # Interoperability with other array libraries
)
```

### Commonly Used Parameters

- **`object`** *(Required)*
  - Data to be converted into a NumPy array.
  - Accepts any **array-like object**:
    - List
    - Tuple
    - Range
    - Existing NumPy array
    - List of tuples, etc.

- **`dtype`** *(Commonly used)*
  - Specifies the desired data type.
  - If omitted (`None`), NumPy automatically infers the data type from the input data.

- **`ndmin`** *(Commonly used)*
  - Specifies the **minimum** number of dimensions.
  - It **does not** specify the exact number of dimensions.
  - If the input already has more dimensions than `ndmin`, NumPy leaves it unchanged.

### Examples

#### 1. Change the data type

```python
np.array([1, 2, 3], dtype=float)
```

Output:

```python
array([1., 2., 3.])
```

---

#### 2. Create a 2D array from a 1D object

```python
np.array([1, 2, 3], ndmin=2)
```

Output:

```python
array([[1, 2, 3]])
```

---

#### 3. `ndmin` does not reduce dimensions

```python
np.array([[1, 2, 3],
          [4, 5, 6]], ndmin=1)
```

Output:

```python
array([[1, 2, 3],
       [4, 5, 6]])
```

The input is already 2D, so `ndmin=1` is ignored.

### Key Points

- `object` is the **only required** parameter.
- `dtype=None` → NumPy chooses an appropriate data type.
- `ndmin` only **adds** dimensions when necessary; it never removes them.
- `np.array()` accepts **array-like objects**, not just Python lists.