In [2]:
import numpy as np

> **Note:**  
> `import numpy as np` must be executed **at least once** before using any NumPy functions in a Python file or Jupyter notebook.
>
> - In a **Python (.py) file**, place the import statement near the top of the file.
> - In a **Jupyter Notebook (.ipynb)**, run the cell containing the import statement at least once per kernel session. If the kernel is restarted, the import cell must be run again.

In [3]:
arr1 = np.array([1,2,3,4,5,6]) # converts an object (list, tuple, list of tuples, range, existing_arrays, etc) to array.
print(arr1)
arr1 # in jupyter lab, the value of last line/expression is printed automatically, if printable.


[1 2 3 4 5 6]


array([1, 2, 3, 4, 5, 6])

NumPy arrays are homogeneous collections of data. We can create them using np.array().

In [4]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr = np.empty((2,3)) # creates Uninitialized array filled with garbage values.
arr

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
       [1.95819673e-306, 1.42413555e-306, 1.78019082e-306]])

### `np.empty()`

Creates an array **without initializing its values**.

```python
np.empty((2, 3))
```

Possible output:

```python
array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
       [1.95819673e-306, 1.42413555e-306, 1.78019082e-306]])
```

> **Note:**
> - The values shown are **garbage values** (whatever happened to be present in memory).
> - They are **unpredictable** and **should not be relied upon**.
> - `np.empty()` is faster than `np.zeros()` because NumPy **does not initialize** the array elements.
> - Always assign values to an `empty` array before using it in computations.

In [6]:
arr = np.full((3,3),7) # creates array filled with a specified value, in this case 7.
arr

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [7]:
# arr3 = np.zeroes(2,3) # wrong spelling of zeros
# arr3

In [8]:
# arr3 = np.zeros(2,3) # no double parenthesis ((2,3))
# arr3
# # func signature of np.zeros is np.zeros(shape, dtype=float).
# # here shape is a tuple (2,3) and dtype is defaulted as floating-point if no second parameter is given.

In [9]:
arr3 = np.zeros((2,3)) # creates NumPy floating-point array and prints 0.0 in a shortened form as 0. 
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
arr3 = np.zeros((2,3), dtype="int") # this fixes the data type as integer
arr3

array([[0, 0, 0],
       [0, 0, 0]])

In [11]:
arr4 = np.zeros(10)
arr4

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
arr4 = np.zeros(10,int) # can also be written as arr4 = np.zeros(10,dtype="int")
arr4

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
arr4 = np.zeros(10,dtype="int")
arr4

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
arr4 = np.zeros(10,dtype="bool")
arr4

array([False, False, False, False, False, False, False, False, False,
       False])

In [15]:
arr4 = np.ones(5,int)
arr4

array([1, 1, 1, 1, 1])

In [16]:
arr4 = np.ones((3,3),int)
arr4

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [17]:
arr5 = np.identity(5) # creates an identity matrix of dim 5.
print(arr5)
print()
arr5 = np.identity(5,int)
print(arr5)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [18]:
arr5 = np.eye(5, dtype = int) # another way to create an identity matrix
arr5

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [19]:
arr5 = np.identity(0)
print(arr5)

[]


In [20]:
arr5 = np.diag([1,2,3]) # creates a diagonal matrix with given elements in array-like object.
arr5

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [21]:
arr6 = np.arange(10)  # Stands for "array range". Creates a NumPy array containing the first 10 whole numbers (0 to 9).
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
arr6 = np.arange(1,10) # Creates a NumPy array from 1 (inclusive) to 10 (exclusive). np.arange(start,stop)
arr6

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
arr6 = np.arange(1,11,1)    # Creates a NumPy array from 1 (inclusive) to 11 (exclusive) with a step of 1. 
                            # np.arange(start,stop,step) . step is 1 by default.
arr6

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
arr6 = np.arange(1,11,2) # Creates a NumPy array from 1 (inclusive) to 11 (exclusive) with a step of 2.
arr6

array([1, 3, 5, 7, 9])

In [25]:
arr6 = np.arange(30,-5,3) # Creates a NumPy array from 30 (inclusive) to -5 (exclusive) with a step of 3.
arr6                      # no possible elements

array([], dtype=int64)

In [26]:
arr6 = np.arange(30,-6,-2) # Creates a NumPy array from 30 (inclusive) to -6 (exclusive) with a step of -2.
arr6

array([30, 28, 26, 24, 22, 20, 18, 16, 14, 12, 10,  8,  6,  4,  2,  0, -2,
       -4])

In [27]:
arr7 = np.linspace(1,10,10) # signature - np.linspace(start, stop, num=50, endpoint=True, dtype=None)
                            # generates 10 equally spaced numbers from 1 to 10 (both inclusive).
arr7

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [28]:
arr7 = np.linspace(1,10,10) # generates 10 equally spaced numbers from 1 to 10 (both inclusive).
arr7

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

signature of linspace() - np.linspace(start, stop, num=50, endpoint=True, dtype=None)

In [29]:
arr7 = np.linspace(1,10,3) # generates 3 equally spaced numbers from 1 to 10 (both inclusive).
arr7

array([ 1. ,  5.5, 10. ])

In [30]:
arr7 = np.linspace(1,100,20) # generates 20 equally spaced numbers from 1 to 100 (both inclusive).
arr7

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

In [31]:
arr7 = np.linspace(100,10,7) # generates 7 equally spaced numbers from 100 to 10 (both inclusive).
arr7

array([100.,  85.,  70.,  55.,  40.,  25.,  10.])

In [32]:
arr7 = np.linspace(100,10,7, endpoint=False) # we can choose to exclude the stop value.
arr7

array([100.        ,  87.14285714,  74.28571429,  61.42857143,
        48.57142857,  35.71428571,  22.85714286])

In [33]:
arr7 = np.linspace(100,10,7, endpoint = False, dtype = int) # The floating-point values are truncated to integers 
                                # because dtype=int. (decimal part is removed, no rounding of values is done).
arr7

array([100,  87,  74,  61,  48,  35,  22])

In [34]:
arr8 = np.random.rand(2,3) # creates an array with random values
arr8

array([[0.53096263, 0.60530183, 0.14359313],
       [0.20615091, 0.48901307, 0.98048097]])

In [35]:
arr8 = np.random.randint(1, 10, size=(2,3)) # creates an array of dim (2,3) with values bw 1(inclusive) & 10(exclusive)
arr8

array([[8, 4, 8],
       [8, 1, 4]], dtype=int32)

## Other Array Creation Functions

- **`np.logspace()`**
  - Creates numbers that are evenly spaced on a **logarithmic scale**.
  - Example:
    ```python
    np.logspace(1, 3, 3)
    # Output: array([  10.,  100., 1000.])
    ```

- **`np.geomspace()`**
  - Creates numbers that form a **geometric progression** (constant ratio).
  - Example:
    ```python
    np.geomspace(1, 1000, 4)
    # Output: array([   1.,   10.,  100., 1000.])
    ```

- **`np.mgrid()`**
  - Creates dense coordinate grids using slice notation.
  - Mainly used for numerical computations and plotting.

- **`np.meshgrid()`**
  - Converts 1D coordinate arrays into coordinate matrices.
  - Commonly used for plotting surfaces, contours, and evaluating functions of two variables.

> **Note:** `logspace()`, `geomspace()`, `mgrid()`, and `meshgrid()` are more advanced functions. They are widely used in scientific computing, data visualization, and machine learning, but are not essential when first learning NumPy.