In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [3]:
print(arr)
print(arr.shape)        # shape of array (dimension of array as tuple).
print(arr.ndim)         # dimension(axes) of array (1-D, 2-D, 3-D, etc).
print(arr.size)         # total number of elements in array.
print(arr.itemsize)     # size (in bytes) of 1 array element.
print(arr.dtype)        # data-type of array.
print(arr.nbytes)       # space taken by array in bytes.
print(arr.astype(float)) # returns a copy of array with all the elements represented as floating-points.

[1 2 3 4 5]
(5,)
1
5
8
int64
40
[1. 2. 3. 4. 5.]


---
## `shape`

Returns the dimensions of an array as a tuple.

> **Remember:**
> - `(5,)` → 1D array with 5 elements.
> - `(2,3)` → 2 rows, 3 columns. (2D array).
> - `()` → Scalar (0D array).

---
## `ndim`

Returns the **number of dimensions (axes)** of an array.

> **Remember:**
>
> - `1` → 1D array (Vector).
> - `2` → 2D array (Matrix).
> - `3` → 3D array (Collection of matrices).
> - `0` → Scalar (Single value).

---

## `size`

Returns the **total number of elements** in an array.

> **Remember:**
>
> - `(5,)` → `size = 5`
> - `(2,3)` → `size = 6` (`2 × 3`)
> - `(2,2,2)` → `size = 8` (`2 × 2 × 2`)
> - `()` → `size = 1` (Scalar)

---

## `itemsize`

Returns the **size (in bytes) of one array element**.

> **Remember:**
>
> - `int64` → `8` bytes
> - `float64` → `8` bytes
> - `int32` → `4` bytes
> - `bool` → `1` byte
> - Depends only on the array's **dtype**, not its shape or size.
---

In [4]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)
print()
print(arr2.shape)
print(arr2.ndim)
print(arr2.size)
print(arr2.itemsize) # prints 8 because dtype is int64.
print(arr2.dtype)  # prints the dtype

[[1 2 3]
 [4 5 6]]

(2, 3)
2
6
8
int64


In [5]:
print(arr2[0].shape)
print(arr2[0].ndim)
print(arr2[0].size)
print(arr2[0].itemsize)

(3,)
1
3
8


In [6]:
print(arr2[1].shape)
print(arr2[1].ndim)
print(arr2[1].size)
print(arr2[1].itemsize)

(3,)
1
3
8


In [7]:
print(arr2[0,1].shape) # single element in array has 0 dimension. The empty tuple () means 0-dimensional (scalar).
print(arr2[0,1].ndim)
print(arr2[0,1].size)
print(arr2[0,1].itemsize)

()
0
1
8


In [8]:
# # ERROR

# print(arr2[2].shape) # out of bounds
# print(arr2[2].ndim) # out of bounds
# print(arr2[2].size) # out of bounds
# print(arr2[2].itemsize) # out of bounds


In [9]:
# # ERROR

# print(10.shape) # treats 10 as start of decimal literal  
# print(10.ndim)
# print(10.size)
# print(10.itemsize)
                # SyntaxError: invalid decimal literal

In [10]:
# # ERROR

# print((10).shape) # treats 10 as int. int has no shape attribute.
# print((10).ndim)
# print((10).size)
# print((10).itemsize)

In [11]:
print(np.array(10).shape) # treats it as 0-dimensional NumPy array. so shape is ().
print(np.array(10).ndim)
print(np.array(10).size)
print(np.array(10).itemsize)

()
0
1
8


In [12]:
arr3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [13]:
print(arr3.shape)
print(arr3.ndim)
print(arr3.size)
print(arr3.itemsize)

(2, 2, 2)
3
8
8


```text
(2, 2, 2)
│  │  │
│  │  └── 2 columns
│  └───── 2 rows
└──────── 2 matrices (depth)
```

In [14]:
arr3 = np.array([ [[1,2,3],[3,4,2]],[[5,6,8],[5,7,8]] ])
print(arr3)
print()
print(arr3.shape)
print()
print(arr3.ndim)
print()
print(arr3.size)
print()
print(arr3.itemsize)

[[[1 2 3]
  [3 4 2]]

 [[5 6 8]
  [5 7 8]]]

(2, 2, 3)

3

12

8


In [15]:
np.array([True,False,True]).itemsize

1

In [16]:
arr4 = np.array([ [[1.4,2],[3.7,4]],[[5.0,6],[7,8.99]] ])
print(arr4)
print('\n\n')
print(arr4.shape)
print(arr4.ndim)
print(arr4.size)
print(arr4.itemsize)
print(arr4.dtype)

[[[1.4  2.  ]
  [3.7  4.  ]]

 [[5.   6.  ]
  [7.   8.99]]]



(2, 2, 2)
3
8
8
float64


## `dtype`

Returns the **data type** of the array elements.

> **Remember:**
>
> - `int64` → 64-bit integer (8 bytes)
> - `float64` → 64-bit floating-point (8 bytes)
> - `bool` → Boolean (`True`/`False`) (1 byte)
> - `str` / `<U...>` → Unicode string
> - All elements in a NumPy array have the **same `dtype`**.

In [17]:
print(arr2)
arr2.dtype

[[1 2 3]
 [4 5 6]]


dtype('int64')

In [ ]:
print(arr3)
arr3.dtype

[[[1 2 3]
  [3 4 2]]

 [[5 6 8]
  [5 7 8]]]


dtype('int64')

In [ ]:
print(arr)
arr.dtype

[1 2 3 4 5]


dtype('int64')

In [20]:
np.array([True,False,True]).dtype

dtype('bool')

### An important function/method related to dtype() - 
## `astype()`

Array method/ function that converts an array to a **new data type**.

**Syntax**

```python
array.astype(dtype)
```

> **Remember:**
>
> - Returns a **new array** (original remains unchanged).
> - `float → int` **truncates**, not rounds.
> - Common types: `int`, `float`, `bool`, `str`.
> - Use `dtype=` while creating an array; use `astype()` to convert an existing array.

### Examples

```python
arr.astype(int)
arr.astype(float)
arr.astype(bool)
arr.astype(str)

# NumPy-specific data types

arr.astype(np.int32)
arr.astype(np.int64)
arr.astype(np.float32)
arr.astype(np.float64)
```

In [21]:
print(arr)
print(arr.astype(float))
print(arr)

[1 2 3 4 5]
[1. 2. 3. 4. 5.]
[1 2 3 4 5]


In [22]:
print(arr2)
arr2.astype(bool)

[[1 2 3]
 [4 5 6]]


array([[ True,  True,  True],
       [ True,  True,  True]])

## `nbytes`

Returns the **total memory occupied** by the array (in bytes).

> **Remember:**
>
> - `nbytes = size × itemsize`
> - Depends on both the **number of elements** and the **data type**.
> - Useful for checking an array's memory usage.


In [23]:
arr = np.array([[1,2,3], [4,5,6]])
print(arr)
print()
print(arr.size,arr.itemsize)
arr.nbytes # returns (size*itemsize)

[[1 2 3]
 [4 5 6]]

6 8


48

In [24]:
arr5 = np.array([[True,False],[False,False]])
print(arr5)
print()
print(arr5.size,arr5.itemsize)
arr5.nbytes # returns (size*itemsize)

[[ True False]
 [False False]]

4 1


4

---
> **Additional method:** It looks like an attribute (has no parentheses), but is actually a shorthand for the `transpose()` function.

## `T`

Returns the **transpose** of the array (rows ↔ columns).

> **Remember:**
>
> - Works only for arrays with `ndim >= 2`.  
(Or more accurately: Transpose works on 1-D arrays too, but a 1-D array remains unchanged because it has only one axis).
> - Transpose swaps rows and columns.
> - `shape (m, n) → (n, m)`

---

In [25]:
arr6 = np.array([[1,2,3],[4,5,6]])
print(arr6)
print()
print(arr6.T)

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]


In [26]:
arr7 = np.array([1,2,3])
print(arr7)
print()
print(arr7.T)  # Does nothing.

[1 2 3]

[1 2 3]
