# NumPy Array vs Python List

| Feature | Python List | NumPy Array |
|---------|-------------|-------------|
| Data type | Can store mixed types | Stores homogeneous (same type) elements |
| Speed | Slower | Faster (optimized in C) |
| Memory | Uses more memory | More memory-efficient |
| Arithmetic | Not element-wise | Element-wise operations |
| Mathematical functions | Limited | Extensive built-in support |
| Dimensions | Mainly 1D (nested lists for higher dimensions) | Supports true N-dimensional arrays |
| Use case | General-purpose programming | Numerical computing, Data Science, ML |

## Examples

### List

```python
lst = [1, 2, 3]

lst * 2
# [1, 2, 3, 1, 2, 3]
```

```python
lst + [4, 5]
# [1, 2, 3, 4, 5]
```

---

### NumPy Array

```python
import numpy as np

arr = np.array([1, 2, 3])

arr * 2
# array([2, 4, 6])
```

```python
arr + 5
# array([6, 7, 8])
```

```python
arr + np.array([4, 5, 6])
# array([5, 7, 9])
```

## Why NumPy is Faster?

- Stores homogeneous data.
- Uses contiguous memory.
- Implemented in optimized C.
- Supports vectorized operations (avoids Python loops).

> **Remember:**
>
> - **List** → General-purpose container.
> - **NumPy Array** → Fast numerical computations.
> - `list * 2` → Repeats the list.
> - `array * 2` → Multiplies each element.

---
## Experimenting to verify the difference between Python lists and NumPy arrays :
---

In [ ]:
import numpy as np
import time     # needed to calculate the time difference.

In [ ]:
a = [i for i in range(10000000)]
b = [i for i in range(10000000,20000000)]
c = []
start = time.time()         # calculates time before starting loop.
for i in range(len(a)):
    c.append(a[i]+b[i])
print(time.time()-start)    # time difference between start and end of loop
                            # avg time diff = 7.5s (fluctuates)


4.981723308563232


In [ ]:
a = np.arange(10000000)
b = np.arange(10000000,20000000)
start = time.time()         # calculates time before starting loop.
c = a + b
print(time.time()-start)    # time difference between start and end of loop.
                            # avg time diff = 1.5s (fluctuates)


0.5023512840270996


ratio of time difference between list and array:
7.5/1.5

In [ ]:
# Ratio of time difference between list and array:
7.5/1.5

5.0

>In this instance, numpy array is 5 times faster than python list.
>
>
>The ratio varies but as we can see numpy arrays are significantly faster than python lists.

In [15]:
import sys       # needed to determine the memory occupancy using getsizeof().
a = [i for i in range(10000000)]
aa = sys.getsizeof(a) 
print(aa)        # prints memory occupied by the list container in bytes: 89095160
b = np.arange(10000000)
bb = sys.getsizeof(b)
print(bb)        # prints memory occupied by the NumPy array (including its data) in bytes: 80000112
print(aa-bb)     # difference in reported memory = 9095048 bytes

89095160
80000112
9095048


In [14]:
b = np.arange(10000000,dtype = np.int32) # using int32 instead of int64.
bb2 = sys.getsizeof(b)
print(bb2)  # 40000112
aa-bb2      # 49095048 -> using int32 saves almost half the space.


40000112


49095048