# NumPy Array vs Python List

| Feature | Python List | NumPy Array |
|---------|-------------|-------------|
| Data type | Can store mixed types | Stores homogeneous (same type) elements |
| Speed | Slower | Faster (optimized in C) |
| Memory | Uses more memory | More memory-efficient |
| Arithmetic | Not element-wise | Element-wise operations |
| Mathematical functions | Limited | Extensive built-in support |
| Dimensions | Mainly 1D (nested lists for higher dimensions) | Supports true N-dimensional arrays |
| Use case | General-purpose programming | Numerical computing, Data Science, ML |

## Examples

### List

```python
lst = [1, 2, 3]

lst * 2
# [1, 2, 3, 1, 2, 3]
```

```python
lst + [4, 5]
# [1, 2, 3, 4, 5]
```

---

### NumPy Array

```python
import numpy as np

arr = np.array([1, 2, 3])

arr * 2
# array([2, 4, 6])
```

```python
arr + 5
# array([6, 7, 8])
```

```python
arr + np.array([4, 5, 6])
# array([5, 7, 9])
```

## Why NumPy is Faster?

- Stores homogeneous data.
- Uses contiguous memory.
- Implemented in optimized C.
- Supports vectorized operations (avoids Python loops).

> **Remember:**
>
> - **List** → General-purpose container.
> - **NumPy Array** → Fast numerical computations.
> - `list * 2` → Repeats the list.
> - `array * 2` → Multiplies each element.