# Indexing

Accesses one or more **specific elements** of an array using their indices.

## Syntax

### 1D Array

```python
arr[index]
```

### 2D Array

```python
arr[row, column]
```

### 3D Array

```python
arr[matrix, row, column]
```

> **Remember:**
>
> - Indexing starts from **0**.
> - Negative indices count from the end.
> - Each comma represents the next dimension (axis).
> - Accessing a single element returns a **scalar**.

## 1D Examples

```python
arr = np.array([10,20,30,40,50])

arr[0]    # 10
arr[2]    # 30
arr[-1]   # 50
arr[-2]   # 40
```

---

## 2D Examples

```python
arr = np.array([[1,2,3],
                [4,5,6]])

arr[0,1]   # 2
arr[1,2]   # 6
arr[-1,-1] # 6
```

---

## 3D Examples

```python
arr = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])

arr[1,0,1] # 6
arr[0,1,0] # 3
```

# Slicing

Extracts a **portion (sub-array)** of an array.

## Syntax

```python
arr[start : stop : step]
```

> **Remember:**
>
> - `start` → Included.
> - `stop` → Excluded.
> - `step` → Increment (default = `1`).
> - `:` means **select all**.
> - Negative indices count from the end.
> - `[::-1]` reverses the array.

---

## 1D Slicing

```python
arr = np.array([10,20,30,40,50])

arr[1:4]   # [20 30 40]
arr[:3]    # [10 20 30]
arr[2:]    # [30 40 50]
arr[::2]   # [10 30 50]
arr[::-1]  # [50 40 30 20 10]
```

---

## 2D Slicing

**Syntax**

```python
arr[row_slice, column_slice]
```

```python
arr = np.array([[1,2,3],
                [4,5,6]])

arr[:,0]      # First column
arr[1,:]      # Second row
arr[:,1:]     # Last two columns
arr[0:2,0:2]  # Top-left 2×2
```

---

## 3D Slicing

**Syntax**

```python
arr[matrix_slice, row_slice, column_slice]
```

```python
arr = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])

arr[0,:,:]   # First matrix
arr[:,:,0]   # First column of every matrix
arr[:,1,:]   # Second row of every matrix
```

# Iteration

Traverses the elements of an array one by one.

> **Remember:**
>
> - Iterating over a **1D** array gives elements.
> - Iterating over a **2D** array gives rows.
> - Iterating over a **3D** array gives matrices.

---

## 1D Iteration

```python
arr = np.array([10,20,30])

for x in arr:
    print(x)
```

Output

```text
10
20
30
```

---

## 2D Iteration

```python
arr = np.array([[1,2,3],
                [4,5,6]])

for row in arr:
    print(row)
```

Output

```text
[1 2 3]
[4 5 6]
```

---

## Iterate over every element

```python
for row in arr:
    for x in row:
        print(x)
```

Output

```text
1
2
3
4
5
6
```

---

# `flat` vs `np.nditer()`

Both can be used to **iterate over every element** of a NumPy array without manually writing nested loops for each dimension.

```python
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

for x in arr.flat:
    print(x)

for x in np.nditer(arr):
    print(x)
```

Both produce:

```text
1
2
3
4
5
6
```

However, they are designed for different purposes:

```text
flat
  → simple flat iteration

np.nditer()
  → configurable / advanced iteration
```

---

## `flat`

`flat` is an **attribute** that provides a flat iterator over all elements.

```python
for x in arr.flat:
    print(x)
```

Output:

```text
1
2
3
4
5
6
```

The original array remains 2-D:

```python
arr.shape
# (2, 3)
```

> **Remember:**
>
> - `flat` is an **attribute**, not a method.
> - Use `arr.flat`, **not** `arr.flat()`.
> - It provides simple iteration over all elements.
> - It can also be used for **flat indexing and assignment**.

### Flat Indexing

```python
arr.flat[0]
# 1

arr.flat[4]
# 5
```

The elements are treated as if they were:

```text
[1, 2, 3, 4, 5, 6]
```

You can also assign through the flat iterator:

```python
arr.flat[2] = 100
```

Now:

```text
[[  1   2 100]
 [  4   5   6]]
```

> **Important:**  
> `flat` does **not** reshape the original array. 
> It only provides a flat(1-D) way of accessing/iterating through its elements.  
> **However**, modifying through `flat indexing` modifies the original array in-place.


---

## `np.nditer()`

`np.nditer()` creates a **configurable iterator** for traversing NumPy arrays.

```python
for x in np.nditer(arr):
    print(x)
```

Output:

```text
1
2
3
4
5
6
```

For basic iteration, it may look almost identical to:

```python
for x in arr.flat:
    print(x)
```

The difference is that `nditer()` provides **additional control over the iteration**.

---

## Difference 1: Iteration Order

Both normally iterate in **C-style (row-major) order**:

```python
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

for x in arr.flat:
    print(x)

# 1 2 3 4 5 6
```

With `nditer()`, however, you can explicitly request a different iteration order.

```python
for x in np.nditer(arr, order='F'):
    print(x)
```

Output:

```text
1
4
2
5
3
6
```

Here `'F'` means **Fortran-style (column-major) order**.

So:

```text
flat
→ simple flat iteration

nditer()
→ can control iteration order
```

---

## Difference 2: Modifying Elements

By default, `nditer()` does not allow you to modify the array elements through the iterator.

For example:

```python
for x in np.nditer(arr):
    x[...] = 0
```

will not work as a normal writable iteration.

You can explicitly request writable access using:

```python
for x in np.nditer(arr, op_flags=['readwrite']):
    x[...] = 0
```

Now the original array can be modified.

For example:

```python
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

for x in np.nditer(arr, op_flags=['readwrite']):
    x[...] *= 2
```

`arr` becomes:

```text
[[ 2  4  6]
 [ 8 10 12]]
```

> **This is one of the important differences:**  
> `nditer()` provides explicit control over whether the iterated elements are **read-only or writable**.

---

## Difference 3: Multiple Arrays

`np.nditer()` can iterate over **multiple arrays simultaneously**.

For example:

```python
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

for x, y in np.nditer([a, b]):
    print(x, y)
```

Output:

```text
1 10
2 20
3 30
```

You can therefore process corresponding elements of multiple arrays together.

```text
a → [1   2   3]
b → [10  20  30]
      ↓   ↓   ↓
     1,10
     2,20
     3,30
```

This is something `flat` is **not designed to provide directly**.

---

## Difference 4: Broadcasting Multiple Arrays

`nditer()` can also work with arrays of **broadcast-compatible shapes**.

For example:

```python
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([10, 20, 30])

for x, y in np.nditer([a, b]):
    print(x, y)
```

Conceptually, `b` is broadcast:

```text
a:             b:

1  2  3        10 20 30
4  5  6        10 20 30
```

and the iterator gives:

```text
1  10
2  20
3  30
4  10
5  20
6  30
```

This ability to iterate over **multiple broadcast-compatible arrays together** is a major reason `nditer()` is more powerful.

---

## Difference 5: `nditer()` Gives More Control

`np.nditer()` has several options that allow you to control how iteration happens.

For example:

```python
np.nditer(
    arr,
    order='F',
    op_flags=['readwrite'] 
)
```
OR,
```python
np.nditer(
    arr,
    order='F',
    op_flags=['readonly'] 
)
```
to control how the iterator accesses the elements.
You can control things such as:

- iteration order
- whether elements are read-only or writable
- how operands are handled
- iteration over multiple arrays
- broadcasting between operands

This makes `nditer()` much more flexible than `flat`.

---

## Side-by-Side Comparison

| Feature                              | `arr.flat` | `np.nditer()` |
| ------------------------------------ | ---------- | ------------- |
| Simple element iteration             | ✅          | ✅             |
| Works with multidimensional arrays   | ✅          | ✅             |
| Flat iteration                       | ✅          | ✅             |
| Change iteration order               | ❌          | ✅             |
| Modify elements                      | ✅          | ✅             |
| Explicit read/write control          | ❌          | ✅             |
| Iterate multiple arrays together     | ❌          | ✅             |
| Handle broadcasting between operands | ❌          | ✅             |
| Simple to use                        | ✅          | More complex  |
| Advanced iteration control           | ❌          | ✅             |

---

## Which One Should You Use?

For **simple iteration**:

```python
for x in arr.flat:
    ...
```

is usually easier and clearer.

Use:

```python
np.nditer()
```

when you need **specific control over how the iteration is performed**, especially when:

- iterating over multiple arrays
- using broadcasting during iteration
- controlling iteration order
- modifying elements through the iterator
- working with more advanced NumPy iteration behavior

> **Key idea:**
>
> `flat` is primarily a **simple convenience for flat iteration**.
>
> `nditer()` is a **general-purpose, configurable NumPy iterator**.

---