In [2]:
import numpy as np

In [3]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,1,1,1,2])

In [4]:
arr1-arr2 # subtracts every i-th element of arr2 from i-th element of arr1.

array([0, 1, 2, 3, 3])

In [5]:
# arr3 = np.array([1,2,3,4,5,6,7])
# arr1-arr3 # Error as shapes are not the same.

In [6]:
arr3 = np.array([1,2,3,4,5,6,7])
print(arr3 - np.array([7,6,5,4,3,2,1]))
print(np.array([7,6,5,4,3,2,1])- arr3)

[-6 -4 -2  0  2  4  6]
[ 6  4  2  0 -2 -4 -6]


In [7]:
arr1-3 # subtracts 3 from all elements

array([-2, -1,  0,  1,  2])

In [8]:
arr1+arr2 # adds i-th element of arr1 with i-th element of arr2

array([2, 3, 4, 5, 7])

In [9]:
arr4 = np.array([1,1,1,1,1,1,1])
arr4 + arr3

array([2, 3, 4, 5, 6, 7, 8])

In [10]:
arr1*arr2 # multiplies i-th element of arr1 with i-th element of arr2

array([ 1,  2,  3,  4, 10])

In [11]:
arr3*arr4

array([1, 2, 3, 4, 5, 6, 7])

In [12]:
arr1*3 # multiples all element of arr1 with 3

array([ 3,  6,  9, 12, 15])

In [13]:
print(arr4)
arr4*10

[1 1 1 1 1 1 1]


array([10, 10, 10, 10, 10, 10, 10])

In [14]:
print(arr1)
arr1*0.5

[1 2 3 4 5]


array([0.5, 1. , 1.5, 2. , 2.5])

In [15]:
arr1*10000000000 # The result must fit within the array's integer dtype, otherwise integer overflow can occur.

array([10000000000, 20000000000, 30000000000, 40000000000, 50000000000])

In [16]:
arr1*(-1)

array([-1, -2, -3, -4, -5])

In [17]:
# print(arr1)
# print(arr4)
# arr1*arr4 # not possible as shapes are not same.

In [18]:
arr1/arr2 # divides every element of arr1 by corresponding element of arr2.

array([1. , 2. , 3. , 4. , 2.5])

In [19]:
arr1/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [20]:
arr1/0.5

array([ 2.,  4.,  6.,  8., 10.])

In [21]:
arr1/1 # always returns floating-point elements, even when not required.

array([1., 2., 3., 4., 5.])

In [22]:
arr1/0 # gives a runtime warning : "RuntimeWarning: divide by zero encountered".

C:\Users\Ravi\AppData\Local\Temp\ipykernel_2296\1423368002.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0 # gives a runtime warning : "RuntimeWarning: divide by zero encountered".


array([inf, inf, inf, inf, inf])

In [23]:
arr = np.arange(10)
arr += 2   # these operations modify the original array. They perform in-place ops.
print(arr)
arr -= 2
print(arr)
arr *= 2

[ 2  3  4  5  6  7  8  9 10 11]
[0 1 2 3 4 5 6 7 8 9]


In [24]:
# arr /= 2
# arr         # Results in error.

### Why does `arr /= 2` give an error?

```python
arr /= 2
```

- `arr /= 2` means: **"Divide each element by 2 and store the result back into the original array."**
- If `arr` has `dtype=int64`, it can only store integers.
- However, `/` always produces **floating-point (`float64`)** values.
- NumPy does not automatically cast the `float64` result back to `int64`, so it raises a `UFuncTypeError`.

**This works:**

```python
arr = arr / 2
```

- A **new array** is created.
- The new array has `dtype=float64`, so it can store the floating-point results.

> **Remember:**
>
> - `arr /= 2` → Modifies the original array (**fails for `int64` arrays**).
> - `arr = arr / 2` → Creates a **new `float64` array** (**works**).
> - `arr //= 2` → Performs integer (floor) division and works with `int64` arrays.

In [25]:
arr = np.arange(10)
print(arr)
arr //= 2 # Sol 1 to above prob: Use floor division. Integer results can be stored back in the original int array.
arr

[0 1 2 3 4 5 6 7 8 9]


array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4])

In [26]:
arr = np.arange(10) 
print(arr)
arr = arr / 2  # Solution 2: Create a new float64 array to store the result.
arr

[0 1 2 3 4 5 6 7 8 9]


array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [27]:
arr = np.arange(10)
print(arr)
arr = arr.astype(float) # Solution 3: Convert the original array to float64
arr /= 2          # Now in-place division works because the array can store float values.
arr

[0 1 2 3 4 5 6 7 8 9]


array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

**NOTE - 
`arr = arr.astype(float)`

**Creates** a new float64 array and assigns it to arr.

In [28]:
print(arr1)
arr1>3 # checks each element for the condition, returns an array of bools.

[1 2 3 4 5]


array([False, False, False,  True,  True])

In [29]:
arr1>=1

array([ True,  True,  True,  True,  True])

In [30]:
arr1==4

array([False, False, False,  True, False])

In [31]:
arr1!=4

array([ True,  True,  True, False,  True])

In [32]:
-arr1 # changes the sign of all elements.

array([-1, -2, -3, -4, -5])

In [33]:
-(-arr1)

array([1, 2, 3, 4, 5])

In [34]:
+arr1

array([1, 2, 3, 4, 5])

In [35]:
arr101 = np.array([1,-2,3,-4,5,-6]).reshape(2,3)
print(arr101)
-arr101

[[ 1 -2  3]
 [-4  5 -6]]


array([[-1,  2, -3],
       [ 4, -5,  6]])

In [36]:
abs(arr101) # converts each element to its absolute value.

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
print(arr1)
(arr1 > 2) & (arr1 <4 ) # logical AND.

[1 2 3 4 5]


array([False, False,  True, False, False])

In [38]:
(arr1 > 2) | (arr1 < 4 ) # logical OR.

array([ True,  True,  True,  True,  True])

In [39]:
~(arr1 > 3) # logical NOT.

array([ True,  True,  True, False, False])

In [40]:
arr5 = np.arange(6).reshape(2,3)
print(arr5)
print()
arr6 = np.arange(6).reshape(2,3)
print(arr6)
print()
arr7 = np.arange(6).reshape(3,2)
print(arr7)

[[0 1 2]
 [3 4 5]]

[[0 1 2]
 [3 4 5]]

[[0 1]
 [2 3]
 [4 5]]


In [41]:
arr5*arr6 # does arr5[i][j]*arr6[i][j] for every i,j in arrays

array([[ 0,  1,  4],
       [ 9, 16, 25]])

In [42]:
# arr5*arr7 # Error. This is not matrix multiplication. Shape needs to be same.

In [43]:
print(arr5)
print(arr5.ndim)
print(arr5.shape)
print()
print(arr7)
print(arr7.ndim)
print(arr7.shape)
print()
print(arr5@arr7)  # '@' is used for 2d matrix multiplication
print()
arr5.dot(arr7) # matrix multipication of arr5 and arr7. Does not change arr5 or arr7.

[[0 1 2]
 [3 4 5]]
2
(2, 3)

[[0 1]
 [2 3]
 [4 5]]
2
(3, 2)

[[10 13]
 [28 40]]



array([[10, 13],
       [28, 40]])

## Matrix Multiplication

NumPy provides several ways to perform matrix multiplication.

### 1. `@` Operator — Recommended

```python
A @ B
```

- Specifically designed for matrix multiplication.
- Most readable and recommended for matrix operations.
- Equivalent to `np.matmul(A, B)`.

### 2. `.dot()` Method

```python
A.dot(B)
```

- Performs NumPy's `dot` operation.
- For 2D arrays, it is equivalent to matrix multiplication.
- It is the **method form** of the `dot` operation.

### 3. `np.matmul()` Function

```python
np.matmul(A, B)
```

- Specifically performs matrix multiplication.
- Equivalent to `A @ B`.
- For 2D arrays, it gives the same result as `np.dot(A, B)`.

### 4. `np.dot()` Function

```python
np.dot(A, B)
```

- Performs NumPy's `dot` operation.
- For 2D arrays, it is equivalent to matrix multiplication.
- It is the **function form** of the `dot` operation.

### `np.dot()` vs `.dot()`

Both perform the same NumPy `dot` operation.

```python
np.dot(A, B)   # Function form
A.dot(B)       # Method form
```

The main difference is how they are accessed:

- `np.dot(A, B)` → `dot()` function from the NumPy module.
- `A.dot(B)` → `dot()` method of the NumPy array `A`.

For 2D arrays:

```python
np.dot(A, B) == A.dot(B)
```

### Example

```python
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])
```

All four produce the same result for these 2D arrays:

```python
A @ B

A.dot(B)

np.matmul(A, B)

np.dot(A, B)
```

Output:

```python
array([[19, 22],
       [43, 50]])
```

### Remember

| Operator / Function | Operation |
|---|---|
| `A * B` | Element-wise multiplication |
| `A @ B` | Matrix multiplication |
| `np.matmul(A, B)` | Matrix multiplication |
| `A.dot(B)` | Dot product; matrix multiplication for 2D arrays |
| `np.dot(A, B)` | Dot product; matrix multiplication for 2D arrays |

> **Tip:** Prefer `@` when you specifically mean matrix multiplication. It makes your intention clear.

In [44]:
# print(arr5.ndim)
# print(arr5.shape)
# print(arr6.ndim)
# print(arr6.shape)
# arr5.dot(arr6) # shape does not align for multipication. Matrix multi not possible.

In [45]:
print(arr4)
arr4.dot(10) # same as arr4*10.

[1 1 1 1 1 1 1]


array([10, 10, 10, 10, 10, 10, 10])

In [46]:
arr1.max() # returns max element in array

np.int64(5)

In [47]:
arr1.min() # returns min element in array

np.int64(1)

In [48]:
arr8 = np.array([1,7,3,5,7,2,3,3,6,2,4,2]).reshape(3,4)
print(arr8)
print()
print(arr8.max(axis=0)) # returns an array containing all max elements col wise.
print()
print(arr8.max(axis=1)) # returns an array containing all max elements row wise.

[[1 7 3 5]
 [7 2 3 3]
 [6 2 4 2]]

[7 7 4 5]

[7 7 6]


In [49]:
print(arr8)
print()
print(arr8.min(axis=0)) # returns an array containing all min elements col wise.
print()
print(arr8.min(axis=1)) # returns an array containing all min elements row wise.

[[1 7 3 5]
 [7 2 3 3]
 [6 2 4 2]]

[1 2 3 2]

[1 2 2]


In [61]:
print(arr8.sum()) # sum of all the elements in the array.
print(arr8.sum(axis=0)) # array of sums of each col.
print(arr8.sum(axis=1)) # array of sums of each row.
print()
print(arr8.prod()) # product of all the elements in the array.
print(arr8.prod(axis=0)) # array of products of each col.
print(arr8.prod(axis=1)) # array of products of each row.

45
[14 11 10 10]
[16 15 14]

1270080
[42 28 36 30]
[105 126  96]


In [51]:
print(arr8.mean()) # mean of all the elements in the array.
print(arr8.mean(axis=0)) # array of mean of each col.
print(arr8.mean(axis=1)) # array of mean of each row.

3.75
[4.66666667 3.66666667 3.33333333 3.33333333]
[4.   3.75 3.5 ]


In [52]:
np.median(arr8) # median of all elements of arr8.

np.float64(3.0)

**Remember** :
>Syntax of `median` is different than that of `mean` or standard deviation (`std`).

In [53]:
print(arr8)
print(arr8.std())   # prints standard deviation of all elements of array. 
                    # axis-based deviation can be calculated.
print(arr8.std(axis = 0)) # calculates and prints the standard deviation down each column.
print(arr8.std(axis = 1)) # calculates and prints the standard deviation down each row.

[[1 7 3 5]
 [7 2 3 3]
 [6 2 4 2]]
1.963203164898291
[2.62466929 2.3570226  0.47140452 1.24721913]
[2.23606798 1.92028644 1.6583124 ]


In [60]:
np.random.seed(1)
arr9 = np.random.uniform(1,20,10).reshape(2,5)
print(arr9)
print()
print(np.round(arr9))       # rounds to nearest int.
print()
print(np.floor(arr9))       # rounds down to nearest int.
print()
print(np.ceil(arr9))        # rounds up to nearest int.

[[ 8.92341809 14.68616538  1.00217312  6.74431888  3.78836193]
 [ 2.7544333   4.53894402  7.56565381  8.53858201 11.23751795]]

[[ 9. 15.  1.  7.  4.]
 [ 3.  5.  8.  9. 11.]]

[[ 8. 14.  1.  6.  3.]
 [ 2.  4.  7.  8. 11.]]

[[ 9. 15.  2.  7.  4.]
 [ 3.  5.  8.  9. 12.]]


---

## `axis` in NumPy

For a 2-D array:

```text
shape = (rows, columns)
        axis 0   axis 1
```

> **Remember:**  
> `axis` tells NumPy **which dimension to collapse/operate along**, not whether the result is a row or column.

```text
axis=0 → collapse rows    → one result per column
axis=1 → collapse columns → one result per row
```

Example:

```python
arr.std(axis=0)  # std of each column
arr.std(axis=1)  # std of each row
```

---

In [ ]:
print(arr6)
np.sin(arr6) # array/matrix of sine values of each element.

[[0 1 2]
 [3 4 5]]


array([[ 0.        ,  0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 , -0.95892427]])

In [ ]:
np.sqrt(arr6) # array/matrix of sqrt of each element. defaults to floating-points.

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798]])

In [ ]:
np.exp(arr6)  # returns array of e^x for every element x in the original array.

array([[  1.        ,   2.71828183,   7.3890561 ],
       [ 20.08553692,  54.59815003, 148.4131591 ]])

In [ ]:
np.exp(arr6).astype(int) # converts result to int (floor value).

array([[  1,   2,   7],
       [ 20,  54, 148]])