In [ ]:
import numpy as np

In [ ]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,1,1,1,2])

In [ ]:
arr1-arr2 # subtracts every i-th element of arr2 from i-th element of arr1.

array([0, 1, 2, 3, 3])

In [ ]:
# arr3 = np.array([1,2,3,4,5,6,7])
# arr1-arr3 # Error as shapes are not the same.

ValueError: operands could not be broadcast together with shapes (5,) (7,) 

In [ ]:
print(arr3 - np.array([7,6,5,4,3,2,1]))
print(np.array([7,6,5,4,3,2,1])- arr3)

[-6 -4 -2  0  2  4  6]
[ 6  4  2  0 -2 -4 -6]


In [ ]:
arr1-3 # subtracts 3 from all elements

array([-2, -1,  0,  1,  2])

In [ ]:
arr1+arr2 # adds i-th element of arr1 with i-th element of arr2

array([2, 3, 4, 5, 7])

In [ ]:
arr4 = np.array([1,1,1,1,1,1,1])
arr4 + arr3

array([2, 3, 4, 5, 6, 7, 8])

In [ ]:
arr1*arr2 # multiplies i-th element of arr1 with i-th element of arr2

array([ 1,  2,  3,  4, 10])

In [ ]:
arr3*arr4

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
arr1*3 # multiples all element of arr1 with 3

array([ 3,  6,  9, 12, 15])

In [ ]:
print(arr4)
arr4*10

[1 1 1 1 1 1 1]


array([10, 10, 10, 10, 10, 10, 10])

In [ ]:
print(arr1)
arr1*0.5

[1 2 3 4 5]


array([0.5, 1. , 1.5, 2. , 2.5])

In [ ]:
arr1*10000000000 # The result must fit within the array's integer dtype, otherwise integer overflow can occur.

array([10000000000, 20000000000, 30000000000, 40000000000, 50000000000])

In [ ]:
arr1*(-1)

array([-1, -2, -3, -4, -5])

In [ ]:
# print(arr1)
# print(arr4)
# arr1*arr4 # not possible as shapes are not same.

In [ ]:
arr1/arr2 # divides every element of arr1 by corresponding element of arr2.

array([1. , 2. , 3. , 4. , 2.5])

In [ ]:
arr1/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [ ]:
arr1/0.5

array([ 2.,  4.,  6.,  8., 10.])

In [ ]:
arr1/1 # always returns floating-point elements, even when not required.

array([1., 2., 3., 4., 5.])

In [ ]:
arr1/0 # gives a runtime warning : "RuntimeWarning: divide by zero encountered".

C:\Users\Ravi\AppData\Local\Temp\ipykernel_20512\2658178464.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0 # gives a runtime warning


array([inf, inf, inf, inf, inf])

In [ ]:
arr = np.arange(10)
arr += 2   # these operations modify the original array. They perform in-place ops.
print(arr)
arr -= 2
print(arr)
arr *= 2

[ 2  3  4  5  6  7  8  9 10 11]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# arr /= 2
# arr         # Results in error.

### Why does `arr /= 2` give an error?

```python
arr /= 2
```

- `arr /= 2` means: **"Divide each element by 2 and store the result back into the original array."**
- If `arr` has `dtype=int64`, it can only store integers.
- However, `/` always produces **floating-point (`float64`)** values.
- NumPy does not automatically cast the `float64` result back to `int64`, so it raises a `UFuncTypeError`.

**This works:**

```python
arr = arr / 2
```

- A **new array** is created.
- The new array has `dtype=float64`, so it can store the floating-point results.

> **Remember:**
>
> - `arr /= 2` → Modifies the original array (**fails for `int64` arrays**).
> - `arr = arr / 2` → Creates a **new `float64` array** (**works**).
> - `arr //= 2` → Performs integer (floor) division and works with `int64` arrays.

In [ ]:
arr = np.arange(10)
print(arr)
arr //= 2 # Sol 1 to above prob: Use floor division. Integer results can be stored back in the original int array.
arr

[0 1 2 3 4 5 6 7 8 9]


array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4])

In [ ]:
arr = np.arange(10) 
print(arr)
arr = arr / 2  # Solution 2: Create a new float64 array to store the result.
arr

[0 1 2 3 4 5 6 7 8 9]


array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [ ]:
arr = np.arange(10)
print(arr)
arr = arr.astype(float) # Solution 3: Convert the original array to float64
arr /= 2          # Now in-place division works because the array can store float values.
arr

[0 1 2 3 4 5 6 7 8 9]


array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

**NOTE - 
`arr = arr.astype(float)`

**Creates** a new float64 array and assigns it to arr.

In [ ]:
print(arr1)
arr1>3 # checks each element for the condition, returns an array of bools.

[1 2 3 4 5]


array([False, False, False,  True,  True])

In [ ]:
arr1>=1

array([ True,  True,  True,  True,  True])

In [ ]:
arr1==4

array([False, False, False,  True, False])

In [ ]:
arr1!=4

array([ True,  True,  True, False,  True])

In [ ]:
-arr1 # changes the sign of all elements.

array([-1, -2, -3, -4, -5])

In [ ]:
-(-arr1)

array([1, 2, 3, 4, 5])

In [ ]:
+arr1

array([1, 2, 3, 4, 5])

In [ ]:
arr101 = np.array([1,-2,3,-4,5,-6]).reshape(2,3)
print(arr101)
-arr101

[[ 1 -2  3]
 [-4  5 -6]]


array([[-1,  2, -3],
       [ 4, -5,  6]])

In [ ]:
abs(arr101) # converts each element to its absolute value.

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
print(arr1)
(arr1 > 2) & (arr1 <4 ) # logical AND.

[1 2 3 4 5]


array([False, False,  True, False, False])

In [ ]:
(arr1 > 2) | (arr1 < 4 ) # logical OR.

array([ True,  True,  True,  True,  True])

In [ ]:
~(arr1 > 3) # logical NOT.

array([ True,  True,  True, False, False])

In [ ]:
arr5 = np.arange(6).reshape(2,3)
print(arr5)
print()
arr6 = np.arange(6).reshape(2,3)
print(arr6)
print()
arr7 = np.arange(6).reshape(3,2)
print(arr7)

[[0 1 2]
 [3 4 5]] 

[[0 1 2]
 [3 4 5]]

[[0 1]
 [2 3]
 [4 5]]


In [ ]:
arr5*arr6 # does arr5[i][j]*arr6[i][j] for every i,j in arrays

array([[ 0,  1,  4],
       [ 9, 16, 25]])

In [ ]:
# arr5*arr7 # Error. This is not matrix multiplication. Shape needs to be same.

In [ ]:
print(arr5)
print(arr5.ndim)
print(arr5.shape)
print()
print(arr7)
print(arr7.ndim)
print(arr7.shape)
print()
print(arr5@arr7)  # '@' is used for 2d matrix multiplication
print()
arr5.dot(arr7) # matrix multipication of arr5 and arr7. Does not change arr5 or arr7.

[[0 1 2]
 [3 4 5]]
2
(2, 3)

[[0 1]
 [2 3]
 [4 5]]
2
(3, 2)

[[10 13]
 [28 40]]



array([[10, 13],
       [28, 40]])

## Matrix Multiplication

NumPy provides **three ways** to perform matrix multiplication.

### 1. `@` Operator (Recommended)

```python
A @ B
```

- Most readable and commonly used.
- Introduced in Python 3.5 specifically for matrix multiplication.

---

### 2. `.dot()` Method

```python
A.dot(B)
```

- Older method for matrix multiplication.
- Equivalent to `A @ B` for 2D arrays.

---

### 3. `np.dot()` Function

```python
np.dot(A, B)
```

- Function form of `.dot()`.
- Also equivalent to `A @ B` for 2D arrays.

---

### Example

```python
A = np.array([[1,2],
              [3,4]])

B = np.array([[5,6],
              [7,8]])
```

All of the following produce the same result:

```python
A @ B

A.dot(B)

np.dot(A, B)
```

Output:

```python
array([[19, 22],
       [43, 50]])
```

> **Remember:**
>
> - `*` → Element-wise multiplication.
> - `@` → Matrix multiplication (**Recommended**).
> - `.dot()` → Older equivalent of `@`.
> - `np.dot()` → Function form of `.dot()`.

In [ ]:
print(arr5.ndim)
print(arr5.shape)
print(arr6.ndim)
print(arr6.shape)
arr5.dot(arr6) # shape does not align for multipication. Matrix multi not possible.

2
(2, 3)
2
(2, 3)


ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [ ]:
print(arr4)
arr4.dot(10) # same as arr4*10.

[1 1 1 1 1 1 1]


array([10, 10, 10, 10, 10, 10, 10])

In [ ]:
arr1.max() # returns max element in array

np.int64(5)

In [ ]:
arr1.min() # returns min element in array

np.int64(1)

In [ ]:
arr8 = np.array([1,7,3,5,7,2,3,3,6,2,4,2]).reshape(3,4)
print(arr8)
print()
print(arr8.max(axis=0)) # returns an array containing all max elements col wise.
print()
print(arr8.max(axis=1)) # returns an array containing all max elements row wise.

[[1 7 3 5]
 [7 2 3 3]
 [6 2 4 2]]

[7 7 4 5]

[7 7 6]


In [ ]:
print(arr8)
print()
print(arr8.min(axis=0)) # returns an array containing all min elements col wise.
print()
print(arr8.min(axis=1)) # returns an array containing all min elements row wise.

[[1 7 3 5]
 [7 2 3 3]
 [6 2 4 2]]

[1 2 3 2]

[1 2 2]


In [ ]:
print(arr8.sum()) # sum of all the elements in the array.
print(arr8.sum(axis=0)) # array of sums of each col.
print(arr8.sum(axis=1)) # array of sums of each row.

45
[14 11 10 10]
[16 15 14]


In [ ]:
print(arr8.mean()) # mean of all the elements in the array.
print(arr8.mean(axis=0)) # array of mean of each col.
print(arr8.mean(axis=1)) # array of mean of each row.

3.75
[4.66666667 3.66666667 3.33333333 3.33333333]
[4.   3.75 3.5 ]


In [ ]:
np.median(arr8) # median of all elements of arr8.

np.float64(3.0)

syntax of median is different than that of mean or standard deviation.

In [ ]:
arr8.std() # returns standard deviation of whole array. axis-based deviation can be calculated.

np.float64(1.963203164898291)

In [ ]:
print(arr6)
np.sin(arr6) # array/matrix of sine values of each element.

[[0 1 2]
 [3 4 5]]


array([[ 0.        ,  0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 , -0.95892427]])

In [ ]:
np.sqrt(arr6) # array/matrix of sqrt of each element. defaults to floating-points.

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798]])

In [ ]:
np.exp(arr6)

array([[  1.        ,   2.71828183,   7.3890561 ],
       [ 20.08553692,  54.59815003, 148.4131591 ]])

In [ ]:
np.exp(arr6).astype(int) # converts result to int (floor value).

array([[  1,   2,   7],
       [ 20,  54, 148]])