# NumPy Operations

## Arithmetic Operations

Performs **element-wise arithmetic**.

```python
arr1 + arr2
arr1 - arr2
arr1 * arr2
arr1 / arr2
arr1 // arr2
arr1 % arr2
arr1 ** arr2
```

### Array vs Scalar

```python
arr + 5
arr - 5
arr * 5
arr / 5
arr // 5
arr % 5
arr ** 2
```

> **Remember:**
>
> - Operations are **element-wise**.
> - `/` always returns `float64`.
> - `//` performs floor division.
> - Arrays must have **compatible shapes**.

---

## Comparison Operations

Returns a **boolean array** after comparing each element.

```python
arr > 3
arr < 3
arr >= 3
arr <= 3
arr == 3
arr != 3
```

Example:

```python
arr = np.array([1,2,3,4,5])

arr > 3
# array([False, False, False, True, True])
```

---

## Boolean Masking ⭐

Uses a boolean array to filter elements.

```python
arr[arr > 3]
```

Output:

```python
array([4, 5])
```

Examples:

```python
arr[arr % 2 == 0]      # Even numbers

arr[arr < 4]           # Values less than 4

arr[(arr > 2) & (arr < 5)]
```

> **Remember:**
>
> - Comparison → Boolean array.
> - Boolean array → Used to filter elements.

---

## Logical Operations

Used with boolean arrays.

```python
(arr > 2) & (arr < 5)

(arr == 2) | (arr == 5)

~(arr > 3)
```

> Use:
>
> - `&` → AND
> - `|` → OR
> - `~` → NOT
>
> **Do not use** `and`, `or`, `not` with NumPy arrays.

---

## Broadcasting ⭐

Allows NumPy to perform operations on arrays of different but **compatible** shapes.

### Scalar Broadcasting

```python
arr + 5
```

Every element is increased by 5.

---

### Same Shape

```python
arr1 + arr2
```

Both arrays must have identical shapes.

---

### Compatible Shapes

```python
arr = np.array([[1,2,3],
                [4,5,6]])

arr + np.array([10,20,30])
```

Output

```python
array([[11,22,33],
       [14,25,36]])
```

The 1D array is broadcast across every row.

---

### Column Broadcasting

```python
arr + np.array([[10],
                [20]])
```

Output

```python
array([[11,12,13],
       [24,25,26]])
```

The column vector is broadcast across every column.

---

### Incompatible Shapes

```python
arr1 = np.array([1,2,3])

arr2 = np.array([1,2])

arr1 + arr2
```

Error

```text
ValueError:
operands could not be broadcast together...
```

> **Remember:**
>
> Broadcasting works only when dimensions are compatible.
>
> Starting from the last dimension, two dimensions are compatible if:
>
> - They are equal, **or**
> - One of them is `1`.

---

## Matrix Operations ⭐

### Element-wise Multiplication

```python
A * B
```

Every corresponding element is multiplied.

---

### Matrix Multiplication

```python
A @ B

# or

A.dot(B)

# or

np.dot(A, B)
```

> **Remember:**
>
> - `*` → Element-wise multiplication.
> - `@` / `.dot()` → Matrix multiplication.

---

## Bitwise Operations

Works on integer arrays.

```python
arr & 1

arr | 1

arr ^ 1

~arr
```

> Mostly used in bit manipulation.

---

## Useful Mathematical Functions

### Maximum & Minimum

```python
np.maximum(arr1, arr2)

np.minimum(arr1, arr2)
```

---

### Powers

```python
np.power(arr, 2)

np.square(arr)
```

---

### Square Root

```python
np.sqrt(arr)
```

---

### Exponential

```python
np.exp(arr)
```

Computes:

\[
e^x
\]

---

### Logarithm

```python
np.log(arr)
```

Computes the **natural logarithm**:

\[
\ln(x)
\]

---

## In-place Operations

```python
arr += 2

arr -= 2

arr *= 2

arr /= 2   # Error for int arrays

arr //= 2
```

### Why does `arr /= 2` fail?

```python
arr /= 2
```

- Divides each element and stores the result back into the original array.
- `/` returns `float64`.
- An `int64` array cannot store `float64` values.
- NumPy raises a `UFuncTypeError`.

### Solutions

#### Solution 1

```python
arr //= 2
```

Uses integer (floor) division.

---

#### Solution 2

```python
arr = arr / 2
```

Creates a new `float64` array.

---

#### Solution 3

```python
arr = arr.astype(float)

arr /= 2
```

Creates a new `float64` array and assigns it to `arr`.

---

# Quick Revision

- Arithmetic operations are **element-wise**.
- Comparison operations return **boolean arrays**.
- Boolean arrays can be used for **masking**.
- Use `&`, `|`, `~` instead of `and`, `or`, `not`.
- Broadcasting allows operations on compatible shapes.
- `*` → Element-wise multiplication.
- `@` / `.dot()` → Matrix multiplication.
- `/` returns `float64`.
- `arr /= 2` fails for `int64` arrays.
- `arr = arr / 2` creates a new `float64` array.
- `astype()` returns a **new array**.