# Basic Shape-Changing Functions

These functions change the **shape**, **size**, or **dimensionality** of a NumPy array.

---

# `reshape()`

Changes the **shape** of an array **without changing its data**.

## Syntax

```python
array.reshape(shape)

# or

array.reshape(rows, columns)

# or

array.reshape(dim1, dim2, dim3, ...)
```

## Parameters

| Parameter | Description |
|-----------|-------------|
| `shape` | Desired new shape. |
| `-1` | NumPy automatically calculates this dimension. |

---

## Rules

### 1. Number of elements must remain the same.

```python
arr = np.arange(12)

arr.reshape(3,4)
arr.reshape(2,6)
arr.reshape(4,3)
arr.reshape(12,1)
arr.reshape(1,12)
arr.reshape(2,2,3)
```

All work because the total number of elements remains **12**.

```python
arr.reshape(5,2)
```

```
ValueError:
cannot reshape array of size 12 into shape (5,2)
```

---

### 2. Does **not** modify the original array.

```python
arr = np.arange(6)

new_arr = arr.reshape(2,3)

print(arr.shape)
# (6,)

print(new_arr.shape)
# (2,3)
```

---

### 3. Using `-1`

NumPy automatically calculates one unknown dimension.

```python
arr.reshape(-1,4)
# Shape -> (3,4)

arr.reshape(2,-1)
# Shape -> (2,6)
```

Only **one** `-1` is allowed.

```python
arr.reshape(-1,-1)
```

```
ValueError
```

---

## Common Shapes

```python
arr.reshape(12,)      # (12,)
arr.reshape(1,12)     # (1,12)
arr.reshape(12,1)     # (12,1)
arr.reshape(3,4)      # (3,4)
arr.reshape(2,2,3)    # (2,2,3)
```

---

## Remember

- Changes **shape only**.
- Number of elements remains unchanged.
- Usually returns a **view**.
- Original array remains unchanged unless reassigned.
- `-1` can be used only once.

---

# `resize()`

There are **two** different resize functions.

---

# 1. `ndarray.resize()`

Modifies the **original array**.

## Syntax

```python
arr.resize(new_shape)
```

### Example

```python
arr = np.arange(6)

arr.resize((2,3))
```

Output

```text
[[0 1 2]
 [3 4 5]]
```

---

### Increasing Size

```python
arr.resize((3,3))
```

Output

```text
[[0 1 2]
 [3 4 5]
 [0 0 0]]
```

New positions are filled with **0**.

---

### Reducing Size

```python
arr.resize((2,2))
```

Output

```text
[[0 1]
 [2 3]]
```

Extra elements are discarded.

---

# 2. `np.resize()`

Returns a **new resized array**.

## Syntax

```python
np.resize(array, new_shape)
```

### Example

```python
arr = np.array([1,2,3])

np.resize(arr,7)
```

Output

```text
[1 2 3 1 2 3 1]
```

Instead of filling zeros,

it **repeats existing elements**.

---

Another Example

```python
np.resize(arr,(2,4))
```

Output

```text
[[1 2 3 1]
 [2 3 1 2]]
```

---

## Difference

| `arr.resize()` | `np.resize()` |
|---------------|---------------|
| Modifies original array | Returns a new array |
| New elements → `0` | New elements → Repeated values |

---

## Remember

- `arr.resize()` modifies the original array.
- `np.resize()` creates a new array.
- `reshape()` keeps the same number of elements.
- `resize()` can increase or decrease the number of elements.

---

# `flatten()`

Converts any array into a **1D array**.

## Syntax

```python
array.flatten(order='C')
```

---

### Example

```python
arr = np.array([[1,2],
                [3,4]])

arr.flatten()
```

Output

```text
[1 2 3 4]
```

---

## Copy Behavior

```python
flat = arr.flatten()

flat[0] = 100
```

Original array remains unchanged.

```text
[[1 2]
 [3 4]]
```

because `flatten()` returns a **copy**.

---

## Order Parameter

Default

```python
order='C'
```

Row-major order

```
1 2
3 4
```

↓

```
1 2 3 4
```

---

Column-major

```python
arr.flatten(order='F')
```

↓

```
1 3 2 4
```

---

## Remember

- Always returns a **1D array**.
- Always returns a **copy**.
- Safe to modify independently.

---

# `ravel()`

Also converts arrays into **1D**.

## Syntax

```python
array.ravel(order='C')
```

---

### Example

```python
arr.ravel()
```

Output

```text
[1 2 3 4]
```

---

## View Behavior

```python
flat = arr.ravel()

flat[0] = 100
```

Original array also changes.

```text
[[100   2]
 [  3   4]]
```

because `ravel()` usually returns a **view**.

If a view cannot be created,

NumPy automatically returns a copy.

---

## Order Parameter

Same as `flatten()`.

```python
order='C'

order='F'
```

---

## Remember

- Always returns **1D**.
- Usually returns a **view**.
- Faster and more memory efficient than `flatten()`.

---

# `flatten()` vs `ravel()`

| Feature | `flatten()` | `ravel()` |
|----------|-------------|-----------|
| Returns | Copy | View (usually) |
| Memory | More | Less |
| Speed | Slower | Faster |
| Original array changes? | No | Yes (if a view is returned) |

---

## Which one should you use?

Use

```python
flatten()
```

when you need an independent array.

Use

```python
ravel()
```

when performance matters and sharing memory is acceptable.

---

# Quick Comparison

| Function | Changes Shape | Changes Original | Returns |
|----------|---------------|------------------|----------|
| `reshape()` | ✔ | ✖ | Usually a view |
| `arr.resize()` | ✔ | ✔ | `None` (modifies in place) |
| `np.resize()` | ✔ | ✖ | New array |
| `flatten()` | ✔ (to 1D) | ✖ | Copy |
| `ravel()` | ✔ (to 1D) | ✖ | View (usually) |

---

# Summary

| Function | Purpose |
|----------|---------|
| `reshape()` | Change shape without changing data or element count. |
| `arr.resize()` | Resize the original array (fills with zeros or truncates). |
| `np.resize()` | Return a resized array (repeats elements if needed). |
| `flatten()` | Convert to a 1D copy. |
| `ravel()` | Convert to a 1D view (usually). |
