# Dimension Manipulation Functions

These functions **change the number of dimensions (axes)** of an array.

Unlike `reshape()`, they **do not rearrange data**. Instead, they **add or remove dimensions**.

These functions are commonly used in **Machine Learning**, **Deep Learning**, and **broadcasting**.

---

# `expand_dims()`

Adds a **new axis (dimension)** to an array.

## Syntax

```python
np.expand_dims(array, axis)
```

### Parameters

| Parameter | Description |
|----------|-------------|
| `array` | Input array. |
| `axis` | Position where the new axis will be inserted. |

---

## Example 1

```python
arr = np.array([1,2,3,4])

arr.shape
```

```
(4,)
```

```python
np.expand_dims(arr, axis=0)
```

Shape

```
(1,4)
```

Output

```text
[[1 2 3 4]]
```

---

## Example 2

```python
np.expand_dims(arr, axis=1)
```

Shape

```
(4,1)
```

Output

```text
[[1]
 [2]
 [3]
 [4]]
```

---

## Negative Axis

```python
np.expand_dims(arr,-1)
```

Same as

```python
np.expand_dims(arr,1)
```

---

## Common Uses

Convert

```
(5,)
```

↓

```
(1,5)
```

or

```
(5,1)
```

Very useful before feeding data into Machine Learning models.

---

## Remember

- Adds one new dimension.
- Original data remains unchanged.
- Commonly used for broadcasting and ML.

---

# `squeeze()`

Removes dimensions whose size is **1**.

## Syntax

```python
np.squeeze(array, axis=None)
```

---

## Example

```python
arr = np.array([[[1,2,3]]])

arr.shape
```

```
(1,1,3)
```

```python
np.squeeze(arr)
```

Shape

```
(3,)
```

Output

```text
[1 2 3]
```

---

## Example

```python
arr = np.zeros((1,5,1))

arr.shape
```

```
(1,5,1)
```

```python
np.squeeze(arr)
```

↓

```
(5,)
```

---

## Using `axis`

```python
np.squeeze(arr, axis=0)
```

Removes only

```
Axis 0
```

---

## Error

```python
arr = np.zeros((2,5))

np.squeeze(arr, axis=0)
```

```
ValueError
```

because

```
Axis 0 has size 2.
```

Only axes having size **1** can be removed.

---

## Remember

- Removes dimensions of size **1** only.
- Does not remove dimensions having size > 1.

---

# `atleast_1d()`

Ensures an object has **at least one dimension**.

## Syntax

```python
np.atleast_1d(array)
```

---

## Example

```python
x = 5

np.atleast_1d(x)
```

Output

```text
[5]
```

Shape

```
(1,)
```

---

If already 1D or higher,

nothing changes.

```python
np.atleast_1d(np.array([1,2,3]))
```

↓

```
(3,)
```

---

## Remember

- Scalar → 1D array.
- Existing arrays remain unchanged.

---

# `atleast_2d()`

Ensures an object has **at least two dimensions**.

## Syntax

```python
np.atleast_2d(array)
```

---

## Example

```python
arr = np.array([1,2,3])

arr.shape
```

```
(3,)
```

```python
np.atleast_2d(arr)
```

Shape

```
(1,3)
```

Output

```text
[[1 2 3]]
```

---

If already 2D,

nothing changes.

---

## Remember

- Converts 1D → Row vector.
- Existing 2D/3D arrays remain unchanged.

---

# `atleast_3d()`

Ensures an object has **at least three dimensions**.

## Syntax

```python
np.atleast_3d(array)
```

---

## Example

```python
arr = np.array([1,2,3])

arr.shape
```

```
(3,)
```

```python
np.atleast_3d(arr)
```

Shape

```
(1,3,1)
```

Output

```text
[[[1]
  [2]
  [3]]]
```

---

Example

```python
arr = np.array([[1,2],
                [3,4]])

np.atleast_3d(arr)
```

Shape

```
(2,2,1)
```

---

## Remember

- Guarantees at least three dimensions.
- Mainly used inside libraries and advanced code.

---

# Comparison

| Function | Purpose |
|----------|---------|
| `expand_dims()` | Adds a new dimension at a specified position. |
| `squeeze()` | Removes dimensions whose size is 1. |
| `atleast_1d()` | Ensures at least one dimension. |
| `atleast_2d()` | Ensures at least two dimensions. |
| `atleast_3d()` | Ensures at least three dimensions. |

---

# Which should I use?

### Add a new axis

```python
np.expand_dims(arr, axis=0)
```

---

### Remove unnecessary dimensions

```python
np.squeeze(arr)
```

---

### Convert scalar to array

```python
np.atleast_1d(x)
```

---

### Convert 1D array to row vector

```python
np.atleast_2d(arr)
```

---

### Guarantee three dimensions

```python
np.atleast_3d(arr)
```

---

# Summary

| Function | Adds Dimension | Removes Dimension | Returns |
|----------|----------------|-------------------|----------|
| `expand_dims()` | ✔ | ✖ | View (usually) |
| `squeeze()` | ✖ | ✔ | View (usually) |
| `atleast_1d()` | If needed | ✖ | Array |
| `atleast_2d()` | If needed | ✖ | Array |
| `atleast_3d()` | If needed | ✖ | Array |