# Joining Arrays

Joining functions combine two or more arrays into a single array.

The arrays must have **compatible shapes**. The exact compatibility depends on the function being used.

---

# `concatenate()`

Joins arrays along an **existing axis**.

This is the **most general** joining function.

## Syntax

```python
np.concatenate((arr1, arr2, ...), axis=0)
```

### Parameters

| Parameter | Description |
|----------|-------------|
| `arrays` | Tuple/List of arrays to join. |
| `axis` | Axis along which arrays are joined. |

---

## axis = 0 (Default)

Join vertically (add more rows).

```python
arr1 = np.array([[1,2],
                 [3,4]])

arr2 = np.array([[5,6],
                 [7,8]])

np.concatenate((arr1, arr2), axis=0)
```

Output

```text
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
```

Shape

```
(4,2)
```

---

## axis = 1

Join horizontally (add more columns).

```python
np.concatenate((arr1, arr2), axis=1)
```

Output

```text
[[1 2 5 6]
 [3 4 7 8]]
```

Shape

```
(2,4)
```

---

## Rules

For

```python
axis=0
```

All **columns** must match.

For

```python
axis=1
```

All **rows** must match.

---

## Remember

- Most flexible joining function.
- Joins along an **existing axis**.
- Does **not** create a new dimension.

---

# `stack()`

Stacks arrays by creating a **new axis**.

Unlike `concatenate()`, `stack()` **increases the number of dimensions**.

## Syntax

```python
np.stack((arr1, arr2), axis=0)
```

---

## Example

```python
arr1 = np.array([1,2,3])

arr2 = np.array([4,5,6])
```

### axis = 0

```python
np.stack((arr1,arr2))
```

Output

```text
[[1 2 3]
 [4 5 6]]
```

Shape

```
(2,3)
```

---

### axis = 1

```python
np.stack((arr1,arr2), axis=1)
```

Output

```text
[[1 4]
 [2 5]
 [3 6]]
```

Shape

```
(3,2)
```

---

## Rules

All arrays must have **exactly the same shape**.

---

## Remember

- Creates a **new axis**.
- Number of dimensions increases by one.

---

# `hstack()`

Stacks arrays **horizontally** (column-wise).

## Syntax

```python
np.hstack((arr1, arr2))
```

---

## Example

```python
arr1 = np.array([[1,2],
                 [3,4]])

arr2 = np.array([[5,6],
                 [7,8]])

np.hstack((arr1,arr2))
```

Output

```text
[[1 2 5 6]
 [3 4 7 8]]
```

Shape

```
(2,4)
```

---

## Rules

Arrays must have the **same number of rows**.

---

## Remember

- Joins columns.
- Opposite of `hsplit()`.

---

# `vstack()`

Stacks arrays **vertically** (row-wise).

## Syntax

```python
np.vstack((arr1, arr2))
```

---

## Example

```python
np.vstack((arr1,arr2))
```

Output

```text
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
```

Shape

```
(4,2)
```

---

## Rules

Arrays must have the **same number of columns**.

---

## Remember

- Joins rows.
- Opposite of `vsplit()`.

---

# `dstack()`

Stacks arrays along the **third dimension (depth)**.

## Syntax

```python
np.dstack((arr1, arr2))
```

---

## Example

```python
arr1 = np.array([[1,2],
                 [3,4]])

arr2 = np.array([[5,6],
                 [7,8]])

np.dstack((arr1,arr2))
```

Output Shape

```
(2,2,2)
```

Visualization

```text
Matrix 1

1 2
3 4

Matrix 2

5 6
7 8
```

---

## Remember

- Creates the third dimension.
- Frequently used with image data.

---

# `column_stack()`

Stacks **1D arrays as columns**.

## Syntax

```python
np.column_stack((arr1, arr2))
```

---

## Example

```python
arr1 = np.array([1,2,3])

arr2 = np.array([4,5,6])

np.column_stack((arr1,arr2))
```

Output

```text
[[1 4]
 [2 5]
 [3 6]]
```

Shape

```
(3,2)
```

---

## Difference from `hstack()`

For **1D arrays**

```python
np.hstack((arr1,arr2))
```

↓

```text
[1 2 3 4 5 6]
```

whereas

```python
np.column_stack((arr1,arr2))
```

↓

```text
[[1 4]
 [2 5]
 [3 6]]
```

---

## Remember

Treats every 1D array as a **column vector**.

---

# `row_stack()`

Stacks arrays as rows.

## Syntax

```python
np.row_stack((arr1, arr2))
```

---

## Important

`row_stack()` is simply an alias for

```python
np.vstack()
```

Both produce identical results.

---

## Example

```python
np.row_stack((arr1,arr2))
```

Same output as

```python
np.vstack((arr1,arr2))
```

---

## Remember

- Alias of `vstack()`.
- Rarely used.

---

# `block()`

Creates complex block matrices.

Useful for combining arrays in a grid-like structure.

## Syntax

```python
np.block([[A, B],
          [C, D]])
```

---

## Example

```python
A = np.array([[1,2]])
B = np.array([[3]])

C = np.array([[4,5]])
D = np.array([[6]])

np.block([[A,B],
          [C,D]])
```

Output

```text
[[1 2 3]
 [4 5 6]]
```

---

## Remember

- Builds arrays like Lego blocks.
- Very useful for constructing large matrices.
- Less common than `concatenate()` or `stack()`.

---

# Comparison

| Function | New Axis | Join Direction |
|----------|----------|----------------|
| `concatenate()` | ❌ | Existing axis |
| `stack()` | ✔ | New axis |
| `hstack()` | ❌ | Horizontal (Columns) |
| `vstack()` | ❌ | Vertical (Rows) |
| `dstack()` | ✔ | Depth (3rd axis) |
| `column_stack()` | ❌ | Columns |
| `row_stack()` | ❌ | Rows (`vstack()`) |
| `block()` | Depends | Grid/Block layout |

---

# Which should I use?

### General joining

```python
np.concatenate()
```

---

### Create a new dimension

```python
np.stack()
```

---

### Join columns

```python
np.hstack()
```

---

### Join rows

```python
np.vstack()
```

---

### Join depth

```python
np.dstack()
```

---

### Convert 1D arrays into columns

```python
np.column_stack()
```

---

### Build complex matrices

```python
np.block()
```

---

# Summary

| Function | Best Use |
|----------|----------|
| `concatenate()` | General-purpose joining. |
| `stack()` | Create a new dimension while joining. |
| `hstack()` | Join arrays side-by-side. |
| `vstack()` | Join arrays one above another. |
| `dstack()` | Join arrays along depth. |
| `column_stack()` | Treat 1D arrays as columns. |
| `row_stack()` | Same as `vstack()`. |
| `block()` | Construct block matrices. |