# Splitting Arrays

Splitting functions divide an array into **multiple smaller arrays**.

They are the opposite of the joining functions (`concatenate()`, `hstack()`, `vstack()`, etc.).

---

# `split()`

Splits an array into **equal-sized** sub-arrays.

## Syntax

```python
np.split(array, sections, axis=0)
```

### Parameters

| Parameter | Description |
|----------|-------------|
| `array` | Input array. |
| `sections` | Number of equal parts or indices where the split occurs. |
| `axis` | Axis along which to split (default = 0). |

---

## Example 1: Equal Split

```python
arr = np.arange(12)

np.split(arr,3)
```

Output

```text
[array([0,1,2,3]),
 array([4,5,6,7]),
 array([8,9,10,11])]
```

Each part has **4 elements**.

---

## Example 2: Split by Indices

```python
np.split(arr,[3,8])
```

Output

```text
[array([0,1,2]),
 array([3,4,5,6,7]),
 array([8,9,10,11])]
```

The indices indicate **where to split**.

---

## 2D Example

```python
arr = np.array([[1,2],
                [3,4],
                [5,6],
                [7,8]])

np.split(arr,2)
```

Output

```text
[array([[1,2],
        [3,4]]),

 array([[5,6],
        [7,8]])]
```

---

## Rules

When using an integer,

the division **must be exact**.

```python
np.split(np.arange(10),3)
```

```
ValueError
```

because

```
10 ÷ 3
```

is not an integer.

---

## Remember

- Equal-sized splits only.
- Opposite of `concatenate()`.
- Supports splitting using indices.

---

# `array_split()`

Splits an array into **unequal parts if necessary**.

Unlike `split()`,

it **does not require equal division**.

## Syntax

```python
np.array_split(array, sections, axis=0)
```

---

## Example

```python
arr = np.arange(10)

np.array_split(arr,3)
```

Output

```text
[array([0,1,2,3]),
 array([4,5,6]),
 array([7,8,9])]
```

Notice

The first part contains one extra element.

---

## Difference

```python
np.split(arr,3)
```

↓

Error

---

```python
np.array_split(arr,3)
```

↓

Works.

---

## Remember

- Allows unequal splits.
- Preferred when equal division is impossible.

---

# `hsplit()`

Splits an array **horizontally (along columns)**.

Opposite of `hstack()`.

## Syntax

```python
np.hsplit(array, sections)
```

---

## Example

```python
arr = np.array([[1,2,3,4],
                [5,6,7,8]])

np.hsplit(arr,2)
```

Output

```text
[array([[1,2],
        [5,6]]),

 array([[3,4],
        [7,8]])]
```

---

## Split by Column Indices

```python
np.hsplit(arr,[1,3])
```

Output

```text
[array([[1],
        [5]]),

 array([[2,3],
        [6,7]]),

 array([[4],
        [8]])]
```

---

## Rules

When using an integer,

the number of **columns** must divide equally.

---

## Remember

- Splits **columns**.
- Opposite of `hstack()`.

---

# `vsplit()`

Splits an array **vertically (along rows)**.

Opposite of `vstack()`.

## Syntax

```python
np.vsplit(array, sections)
```

---

## Example

```python
arr = np.array([[1,2],
                [3,4],
                [5,6],
                [7,8]])

np.vsplit(arr,2)
```

Output

```text
[array([[1,2],
        [3,4]]),

 array([[5,6],
        [7,8]])]
```

---

## Split by Row Indices

```python
np.vsplit(arr,[1,3])
```

Output

```text
[array([[1,2]]),

 array([[3,4],
        [5,6]]),

 array([[7,8]])]
```

---

## Rules

When using an integer,

the number of **rows** must divide equally.

---

## Remember

- Splits **rows**.
- Opposite of `vstack()`.

---

# `dsplit()`

Splits an array along the **third axis (depth)**.

Opposite of `dstack()`.

## Syntax

```python
np.dsplit(array, sections)
```

---

## Example

```python
arr = np.arange(24).reshape(2,3,4)

arr.shape
```

```
(2,3,4)
```

```python
np.dsplit(arr,2)
```

Output Shapes

```
(2,3,2)

(2,3,2)
```

The third dimension

```
4
```

is split into

```
2 + 2
```

---

## Rules

Works only for arrays having

```
3 or more dimensions.
```

---

## Remember

- Splits the **depth**.
- Opposite of `dstack()`.

---

# Comparison

| Function | Split Direction | Opposite |
|----------|-----------------|----------|
| `split()` | Any axis | `concatenate()` |
| `array_split()` | Any axis | `concatenate()` |
| `hsplit()` | Columns | `hstack()` |
| `vsplit()` | Rows | `vstack()` |
| `dsplit()` | Depth | `dstack()` |

---

# Which should I use?

### Equal-sized split

```python
np.split()
```

---

### Unequal split

```python
np.array_split()
```

---

### Split columns

```python
np.hsplit()
```

---

### Split rows

```python
np.vsplit()
```

---

### Split depth

```python
np.dsplit()
```

---

# Summary

| Function | Best Use |
|----------|----------|
| `split()` | Equal-sized splits. |
| `array_split()` | Unequal-sized splits. |
| `hsplit()` | Split columns. |
| `vsplit()` | Split rows. |
| `dsplit()` | Split depth (3D arrays). |