# Repeating Arrays

These functions repeat array elements or entire arrays.

They are useful when generating patterns, duplicating data, or preparing arrays for broadcasting.

---

# `repeat()`

Repeats **individual elements** of an array.

## Syntax

```python
np.repeat(array, repeats, axis=None)
```

### Parameters

| Parameter | Description |
|----------|-------------|
| `array` | Input array. |
| `repeats` | Number of times each element is repeated. Can be an integer or a sequence. |
| `axis` | Axis along which repetition occurs (default = `None`, flattens first). |

---

## Example 1: Repeat Each Element

```python
arr = np.array([1,2,3])

np.repeat(arr,2)
```

Output

```text
[1 1 2 2 3 3]
```

Each element is repeated **twice**.

---

## Example 2: Different Repetition Counts

```python
np.repeat(arr,[1,2,3])
```

Output

```text
[1 2 2 3 3 3]
```

Meaning

- `1` → repeated once
- `2` → repeated twice
- `3` → repeated three times

---

## Example 3: Repeat Rows

```python
arr = np.array([[1,2],
                [3,4]])

np.repeat(arr,2,axis=0)
```

Output

```text
[[1 2]
 [1 2]
 [3 4]
 [3 4]]
```

Rows are repeated.

---

## Example 4: Repeat Columns

```python
np.repeat(arr,2,axis=1)
```

Output

```text
[[1 1 2 2]
 [3 3 4 4]]
```

Columns are repeated.

---

## Remember

- Repeats **elements**, not the entire array.
- Supports different repetition counts.
- Can repeat along rows or columns using `axis`.

---

# `tile()`

Repeats the **entire array**.

Unlike `repeat()`, it copies the complete array as a block.

## Syntax

```python
np.tile(array, reps)
```

### Parameters

| Parameter | Description |
|----------|-------------|
| `array` | Input array. |
| `reps` | Number of repetitions. Can be an integer or a tuple. |

---

## Example 1: Repeat Entire Array

```python
arr = np.array([1,2,3])

np.tile(arr,2)
```

Output

```text
[1 2 3 1 2 3]
```

The whole array is repeated.

---

## Example 2: Repeat Three Times

```python
np.tile(arr,3)
```

Output

```text
[1 2 3 1 2 3 1 2 3]
```

---

## Example 3: Repeat Rows

```python
arr = np.array([[1,2],
                [3,4]])

np.tile(arr,(2,1))
```

Output

```text
[[1 2]
 [3 4]
 [1 2]
 [3 4]]
```

The entire matrix is repeated vertically.

---

## Example 4: Repeat Columns

```python
np.tile(arr,(1,2))
```

Output

```text
[[1 2 1 2]
 [3 4 3 4]]
```

The entire matrix is repeated horizontally.

---

## Example 5: Repeat Rows and Columns

```python
np.tile(arr,(2,3))
```

Output

```text
[[1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]]
```

The array is repeated

- 2 times vertically
- 3 times horizontally

---

## Remember

- Repeats the **whole array**.
- Very useful for creating repeating patterns.
- `reps` may be an integer or a tuple.

---

# `repeat()` vs `tile()`

| Feature | `repeat()` | `tile()` |
|---------|------------|----------|
| Repeats | Individual elements | Entire array |
| Preserves original pattern | ❌ | ✔ |
| Supports `axis` | ✔ | ❌ (uses `reps` tuple instead) |
| Common use | Duplicate elements | Repeat complete arrays |

---

## Example

```python
arr = np.array([1,2,3])
```

### `repeat()`

```python
np.repeat(arr,2)
```

Output

```text
[1 1 2 2 3 3]
```

---

### `tile()`

```python
np.tile(arr,2)
```

Output

```text
[1 2 3 1 2 3]
```

---

# Which should I use?

### Repeat each element

```python
np.repeat()
```

---

### Repeat the entire array

```python
np.tile()
```

---

# Summary

| Function | Purpose |
|----------|---------|
| `repeat()` | Repeat individual elements. |
| `tile()` | Repeat the entire array. |

---

# Complete Reshaping & Manipulation Functions Covered

## Shape Changing

- `reshape()`
- `resize()`
- `flatten()`
- `ravel()`

---

## Axis Manipulation

- `transpose()`
- `.T`
- `swapaxes()`
- `moveaxis()`

---

## Dimension Manipulation

- `expand_dims()`
- `squeeze()`
- `atleast_1d()`
- `atleast_2d()`
- `atleast_3d()`

---

## Joining Arrays

- `concatenate()`
- `stack()`
- `hstack()`
- `vstack()`
- `dstack()`
- `column_stack()`
- `row_stack()`
- `block()`

---

## Splitting Arrays

- `split()`
- `array_split()`
- `hsplit()`
- `vsplit()`
- `dsplit()`

---

## Repeating Arrays

- `repeat()`
- `tile()`