In [1]:
import numpy as np

In [2]:
arr1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr1)
print("\nshape = ", arr1.shape)
print("dimension = ",arr1.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

shape =  (3, 4)
dimension =  2


In [3]:
arr1.ravel()  # Returns a 1-D view of arr1 whenever possible.
              # If a view cannot be created, it returns a copy.
              # Modifying the returned array changes arr1 only if it is a view.

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
arr2 = arr1.ravel()  # returns a view of the array if possible and stores it in arr2.
print(arr1)          # ravel() itself doesn't modify the original array,
                     # but modifications to arr2 can affect arr1 if arr2 is a view.
print(arr2)
print("\nshape of arr1 = ", arr1.shape)
print("dimension of arr1 = ", arr1.ndim)
print("\nshape of arr2 = ", arr2.shape)
print("dimension of arr2 = ", arr2.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]

shape of arr1 =  (3, 4)
dimension of arr1 =  2

shape of arr2 =  (12,)
dimension of arr2 =  1


In [5]:
arr1.ravel() # no change if original array was already 1-D.

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [6]:
arr1.flatten() # returns a 1-D copy of original array.

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [7]:
print(arr1)
print()
print(arr1.reshape(4,3)) # changes the shape of array to another compatible shape.
print()
print(arr1) # no change in original array.

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [8]:
arr1.reshape(12,) # 1-D array. 1 row containing all elements (here 12 is the size of array).

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [9]:
print(arr1.reshape(12,1)) # 12 rows, 1 col

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]


In [10]:
print(arr1.reshape(12,-1)) # 12 rows, 1 col. same as above. python infers the second dim.

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]


In [11]:
print(arr1.reshape(6,2)) # 6 rows, 2 col

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [12]:
print(arr1.reshape(2,6)) # 2 rows, 6 cols

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [13]:
print(arr1.reshape(2,-1)) # 2 rows, 6 cols. python infers the dim if its written as -1.


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [14]:
print(arr1.reshape(1,12)) # 1 row, 12 cols

[[ 1  2  3  4  5  6  7  8  9 10 11 12]]


In [15]:
print(arr1.reshape(-1,12)) # 1 row, 12 col. python infers the dim if its written as -1.


[[ 1  2  3  4  5  6  7  8  9 10 11 12]]


In [16]:
# print(arr1.reshape(4,4))    # shape (4,4) is incompatible for array of size 12.
#                     # Error - ValueError: cannot reshape array of size 12 into shape (4,4).

In [17]:
arr3 = arr1.reshape(2,2,3) # creates a 3-D array of shape (2,2,3).
print(arr1)
print()
print(arr3.shape)
print(arr3.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

(2, 2, 3)
3


In [18]:
arr1.reshape(2,2,-1) # same as above

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [19]:
# arr1.reshape(2,-1,-1) # python cannot infer multiple unknown dims.
#                     # ValueError: can only specify one unknown dimension

In [20]:
print(arr1)
arr1.transpose() # returns transpose of array. original array remains unmodified.

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [21]:
arr1.T # Shortcut for arr1.transpose() on NumPy arrays.

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [22]:
arr1.T.T # returns original array (arr1)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [23]:
arr5 = np.arange(1,7).reshape(2,3)
print(arr5)
arr6 = np.arange(11,17).reshape(2,3)
print(arr6)
np.hstack((arr5,arr6)) #stacks arr6 after arr5, horizontally.
                # Requires the arrays which have to be stacked to be put inside a tuple as argument.

[[1 2 3]
 [4 5 6]]
[[11 12 13]
 [14 15 16]]


array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16]])

In [24]:
# np.hstack(arr5,arr6) # arrays not passed in a single tuple. 
#                     # TypeError: hstack() takes 1 positional argument but 2 were given

In [25]:
# print(arr1.shape)
# print(arr5.shape)
# np.hstack((arr1,arr5)) # Arrays must have the same number of rows (same size along axis 0) for horizontal stacking.
#                     # In other words, Arrays must have compatible shapes for horizontal stacking.

In [26]:
arr4 = np.arange(1,10).reshape(3,3)
print(arr1)
print()
print(arr1.shape)
print()
print(arr4)
print()
print(arr4.shape)
np.hstack((arr1,arr4))


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

(3, 4)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

(3, 3)


array([[ 1,  2,  3,  4,  1,  2,  3],
       [ 5,  6,  7,  8,  4,  5,  6],
       [ 9, 10, 11, 12,  7,  8,  9]])

In [27]:
print(arr4.shape)
print(arr5.shape)
print()
print(arr4)
print()
print(arr5)
np.vstack((arr4,arr5)) # stacks the arrays vertically. arrays should have equal no. of cols.


(3, 3)
(2, 3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3]
 [4 5 6]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6]])

In [28]:
print(arr6.shape)
print(arr6)
np.vstack((arr4,arr5,arr6))

(2, 3)
[[11 12 13]
 [14 15 16]]


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16]])

In [29]:
# print(arr3.shape) # arr3 is a 3-D array
# print(arr3.ndim)
# print(arr4.ndim)
# np.vstack((arr4,arr3)) # arr4 is 2-D. stacking arrays of different dims isn't valid.
# # ValueError: all the input arrays must have same number of dimensions, but the array 
# # at index 0 has 2 dimension(s) and the array at index 1 has 3 dimension(s)

In [30]:
arr7 = np.arange(100,124).reshape(4,-1)
print(arr7)
print(arr7.shape)
print(np.hsplit(arr7,2)) # Splits an array horizontally, i.e., along columns into 2 parts.


[[100 101 102 103 104 105]
 [106 107 108 109 110 111]
 [112 113 114 115 116 117]
 [118 119 120 121 122 123]]
(4, 6)
[array([[100, 101, 102],
       [106, 107, 108],
       [112, 113, 114],
       [118, 119, 120]]), array([[103, 104, 105],
       [109, 110, 111],
       [115, 116, 117],
       [121, 122, 123]])]


In [ ]:
np.hsplit(arr7,2) # Splits an array horizontally, i.e., along columns into 2 parts.

[array([[100, 101, 102],
        [106, 107, 108],
        [112, 113, 114],
        [118, 119, 120]]),
 array([[103, 104, 105],
        [109, 110, 111],
        [115, 116, 117],
        [121, 122, 123]])]

In [32]:
print(np.vsplit(arr7,2)) # Splits an array vertically, i.e., along rows into 2 parts.
print(arr7)

[array([[100, 101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110, 111]]), array([[112, 113, 114, 115, 116, 117],
       [118, 119, 120, 121, 122, 123]])]
[[100 101 102 103 104 105]
 [106 107 108 109 110 111]
 [112 113 114 115 116 117]
 [118 119 120 121 122 123]]


In [33]:
# print(np.vsplit(arr7,3)) # can't split 4 rows into 3 equal parts.
#                         # ValueError: array split does not result in an equal division.

In [34]:
print(arr7)
np.hsplit(arr7, [1,3]) # first split after 1st col then after 3rd col.

[[100 101 102 103 104 105]
 [106 107 108 109 110 111]
 [112 113 114 115 116 117]
 [118 119 120 121 122 123]]


[array([[100],
        [106],
        [112],
        [118]]),
 array([[101, 102],
        [107, 108],
        [113, 114],
        [119, 120]]),
 array([[103, 104, 105],
        [109, 110, 111],
        [115, 116, 117],
        [121, 122, 123]])]

In [35]:
print(arr7)
np.vsplit(arr7, [1,3]) # first split after 1st row then after 3rd row.

[[100 101 102 103 104 105]
 [106 107 108 109 110 111]
 [112 113 114 115 116 117]
 [118 119 120 121 122 123]]


[array([[100, 101, 102, 103, 104, 105]]),
 array([[106, 107, 108, 109, 110, 111],
        [112, 113, 114, 115, 116, 117]]),
 array([[118, 119, 120, 121, 122, 123]])]