In [1]:
import numpy as np

In [2]:
arr = np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [3]:
arr[[1,2,3]] # row 1, 2, 3. Makes a copy of the original array. 
             # No chance of modification (by mistake) in the original.


array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [4]:
arr[[1]]  # only row 1

array([[ 6,  7,  8,  9, 10]])

In [5]:
arr[[-1,-2,-3,-4,-5]]  # returns whole array with reversed rows.

array([[21, 22, 23, 24, 25],
       [16, 17, 18, 19, 20],
       [11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

In [6]:
arr[[1],:]  # same as arr[[1]]

array([[ 6,  7,  8,  9, 10]])

In [7]:
arr[[0],[0]] # returns element at row 0 col 0 as array

array([1])

In [8]:
arr[[0],[4]] # array containing element at row 0 col 4

array([5])

In [9]:
arr[[0,1],[0,1]] # array containing elements at (0,0) ans (1,1)

array([1, 7])

In [10]:
arr[[1,3,3,2],[0,4,0,3]] # array containing elements at (1,0), (3,4), (3,0), (2,3)

array([ 6, 20, 16, 14])

In [11]:
arr[[0,3],1:4] # for whole row 0 & 3 element of col 1 to 3

array([[ 2,  3,  4],
       [17, 18, 19]])

In [12]:
arr[:,[0]] # col 0

array([[ 1],
       [ 6],
       [11],
       [16],
       [21]])

In [13]:
arr[:,[0,1,4]] # array containing elements in cols 0, 1, 4

array([[ 1,  2,  5],
       [ 6,  7, 10],
       [11, 12, 15],
       [16, 17, 20],
       [21, 22, 25]])

In [14]:
arr[[0,2]] # returns an array containing only rows 0 and 2 of array arr.

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [15]:
arr[[0,2]][[0,1],[0,4]]  # returns the array of elements (0,0), (1,4) from arr[[0,2]].

array([ 1, 15])

In [16]:
arr[[0,2]][[1],[1,2]]  # returns the array of elements (1,1), (1,2) from arr[[0,2]].
                       # grouping is done due to broadcasting.

array([12, 13])

In [17]:
arr[[[1],[0]], [[1,3,2]]] # selects a 2 × 3 grid of positions, rather than pairing only corresponding indices.
                # rows = [[1],[0]] . shape = (2,1) - 2 inner lists/rows, each containing 1 element/col.
                #  cols = [[1,3,2]] . shape = 1,3 - 1 row, 3 cols.
                # these shapes can be broadcasted together - 
                # (1,1)  (1,3)  (1,2) 
                # (0,1)  (0,3)  (0,2)

array([[7, 9, 8],
       [2, 4, 3]])

**NOTE -**

>Multiple integer index arrays are broadcasted together, and the resulting shape determines how many elements are selected.

In [18]:
arr[[[1],[0]], :]

array([[[ 6,  7,  8,  9, 10]],

       [[ 1,  2,  3,  4,  5]]])

In [19]:
arr[[[1],[0]], [[1]]]

array([[7],
       [2]])

In [20]:
arr[[[1],[0]], [1]]

array([[7],
       [2]])

In [21]:
arr[[[1],[0]], 1]

array([[7],
       [2]])

In [22]:
# arr[[[1,0]], [[1,3,2]]] # cannot be broadcasted together.
#         # IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (1,2) (1,3).

In [23]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [24]:
arr[arr>0] # This is indexing using boolean array.

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [25]:
arr[arr>21]  # returns an array containing all elements for which the condition is true.

array([22, 23, 24, 25])

In [26]:
arr[arr>=21]

array([21, 22, 23, 24, 25])

In [27]:
arr[arr<21]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [28]:
arr[arr<0]

array([], dtype=int64)

In [29]:
arr1 = np.random.randint(low = 1, high = 100, size = 20).reshape(4,5)
                # same as: arr1 = np.random.randint(1,100,20).reshape(4,5)
                # we can specify datatype as int64 by doing: randint(1,100,20, dtype = np.int64)
arr1

array([[43, 78, 73, 81, 17],
       [44, 71, 96, 45, 34],
       [80, 42, 64, 13, 46],
       [57, 80, 95, 29, 23]], dtype=int32)

In [30]:
arr1[arr1>45]

array([78, 73, 81, 71, 96, 80, 64, 46, 57, 80, 95], dtype=int32)

In [31]:
arr1[arr1>100]

array([], dtype=int32)

In [32]:
# arr1[arr>10]        # can't pass a different array with incompatible shape.
#                     # IndexError: boolean index did not match indexed array along axis 0; size of axis is 4.
#                     # but size of corresponding boolean axis is 5.

In [33]:
arr2 = np.random.randint(1,50,20,dtype = np.int8).reshape(4,5)
arr3 = np.arange(1,21).reshape(4,5)
print(arr2)
print()
print(arr3)
print()            
print(arr3[arr2<10])    # Uses arr2's boolean mask to select elements from arr3.
print()
print(arr2[arr3<10])    # Uses arr3's boolean mask to select elements from arr2.
            # arr2 and arr3 have the same shape, so either can be used as a boolean mask for the other.

[[32 43  1  6 41]
 [26 47 13 36 38]
 [47 35  3 28 12]
 [ 9 13 16 33 20]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[ 3  4 13 16]

[32 43  1  6 41 26 47 13 36]


In [34]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [35]:
arr[(arr>10) & (arr%2 == 0)] # returns an array containing all elements for which both the conditions are true.

array([12, 14, 16, 18, 20, 22, 24])

**PRO-TIP :**

> Always use braces. Even when you think its unnecessary. 

(Its very very necessary in this case).

In [36]:
# arr[arr>10 & arr%2 == 0]  # No parenthesis == precedence issues.
#                           # ValueError: The truth value of an array with more than one element is ambiguous. 
#                           # Use a.any() or a.all()

In [37]:
arr[(arr>10) & (arr%3 == 0)] # returns an array containing all elements for which both the conditions are true.

array([12, 15, 18, 21, 24])

In [38]:
# arr[(arr>10) && (arr%2 == 0)] # doesn't work.
# arr[(arr>10) and (arr%2 == 0)] # doesn't work.
                    # '&&' is the logical AND operator in C/C++, not NumPy's element-wise AND.
                    # 'and' is also not suitable for element-wise NumPy boolean arrays.
                    # '&' performs element-wise AND between NumPy boolean arrays.

---
## `and` vs `&` vs `&&`

| Operator | Used in | Meaning |
|----------|---------|---------|
| `and` | Python | Logical AND for single boolean values |
| `&` | NumPy | Element-wise AND between boolean arrays |
| `&&` | C/C++ | Logical AND operator |

### NumPy Boolean Conditions

```python
arr[(arr > 10) & (arr % 2 == 0)]
```

> **Remember:**
>
> - Use `&` for **element-wise AND** with NumPy arrays.
> - Put each condition inside **parentheses**.
> - `and` cannot be used with NumPy boolean arrays.
> - `&&` is not a Python operator; it is used for logical AND in C/C++.

-----------

In [39]:
arr[(arr>20) | (arr%5 == 0)] 

array([ 5, 10, 15, 20, 21, 22, 23, 24, 25])

In [40]:
arr[(arr>=15) | (arr%2 != 0)] 

array([ 1,  3,  5,  7,  9, 11, 13, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
       25])

---

## Element-by-Element Condition Matching

NumPy conditions are evaluated **element by element**.

```python
arr >= 15
```

Each element is checked separately and produces a corresponding `True` or `False`.

Example:

```python
arr = np.array([10, 15, 8, 21])

arr >= 15
# [False, True, False, True]
```

> **Remember:**
> Each boolean value corresponds to the element at the **same position** in the original array.

```python
arr[arr >= 15]
# [15, 21]
```

The `True` positions are selected; `False` positions are excluded.

### With multiple conditions

```python
arr[(arr >= 15) | (arr % 2 != 0)]
```

`|` performs **element-by-element OR**.

```text
(arr >= 15)      → [F, T, F, T]
(arr % 2 != 0)   → [F, T, F, T]
                    ↓  ↓  ↓  ↓
OR                → [F, T, F, T]
```

Result:

```python
[15, 21]
```

At each position, the element is selected if **at least one condition is True**.



---

In [41]:
arr5 = np.arange(1,13).reshape(3,4)
print(arr5)
print()
print(arr5[((arr5 % 2) == 0)])
print()
arr5[((arr5 % 2) == 0)] = 0 # Replaces every even element in the original array with 0.
print(arr5)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[ 2  4  6  8 10 12]

[[ 1  0  3  0]
 [ 5  0  7  0]
 [ 9  0 11  0]]


**NOTE -**

> You can use the boolean mask not only to select elements, but also to modify all matching elements in-place.

***Boolean indexing can be used for both selecting and modifying elements.***