#### 1. Import the numpy package under the name `np`.

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration

In [2]:
print(np.__version__)
np.show_config()

2.5.1
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-h1i__5an/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-h1i__5an/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.33.112.0  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=24
    pc file directory: D:/a/numpy-release/numpy-release/.openblas
    version: 0.3.33.112.0
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-h1i__5an/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-h1i__5an/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas 

#### 3. Create a null vector of size 10.

In [3]:
arr = np.zeros(10,int)
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 4. How to find the memory size of any array.

In [4]:
print(arr.nbytes)

80


#### 5. How to get the documentation of the numpy add function from the command line?

In [5]:
np.info(np.add)

# Another(older) way of doing it -
!python -c "import numpy; numpy.info(numpy.add)"

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 10 but the fifth value which is 1.

In [6]:
arr = np.zeros(10)
arr[4]=1
print(arr)

# Another way of doing it - 
np.eye(10,dtype = int)[4]  # returns the 4th row of 10x10 identity matrix, in which 5th element is 1 and rest are 0.

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

#### 7. Create a vector with values ranging from 10 to 49.

In [7]:
arr = np.arange(10,50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last).

In [8]:
arr = np.arange(50)
print(arr)
arr = arr[::-1]
arr

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8

In [9]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0].

In [10]:
print(np.argwhere(np.array([1,2,0,0,4,0]) != 0))

# Alternative (better) way of doing it - 
np.nonzero(np.array([1,2,0,0,4,0]))

[[0]
 [1]
 [4]]


(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix.

In [11]:
arr = np.identity(3,int)
arr

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

#### 12. Create a 3x3x3 array with random values.

In [12]:
arr = np.random.random((3,3,3))
arr

array([[[0.10262344, 0.75296835, 0.20921232],
        [0.86398699, 0.40764369, 0.73659847],
        [0.92707357, 0.22501486, 0.84212981]],

       [[0.40762749, 0.77028066, 0.40578721],
        [0.23074924, 0.98437666, 0.76626889],
        [0.64924956, 0.51075575, 0.94529976]],

       [[0.92406832, 0.90070006, 0.17492817],
        [0.67265937, 0.37250393, 0.64839505],
        [0.38091584, 0.19264703, 0.31249694]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values.

In [13]:
arr = np.random.random((10,10))
print("min = ", np.min(arr))   # can also be written as : print("min = ", arr.min())
print("max = ", np.max(arr))

min =  0.015852866427403023
max =  0.9971027905912375


#### 14. Create a random vector of size 30 and find the mean value.

In [14]:
arr = np.random.random(30)
np.mean(arr)

np.float64(0.5715506414017694)

#### 15. Create a 2d array with 1 on the border and 0 inside.

In [15]:
arr = np.ones((5,6),dtype= int)
arr[1:-1,1:-1] = 0
print(arr)
print()
# Another way to do this is - 
arr = np.zeros((5,6),dtype= int)
arr[0, :] = arr[-1, :] = 1
arr[:, 0] = arr[:, -1] = 1
print(arr)

[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]

[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [16]:
arr = np.arange(1,16).reshape(3,5)
print(arr)
np.pad(arr, pad_width=1, mode='constant', constant_values=0)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


array([[ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5,  0],
       [ 0,  6,  7,  8,  9, 10,  0],
       [ 0, 11, 12, 13, 14, 15,  0],
       [ 0,  0,  0,  0,  0,  0,  0]])

#### 17. What is the result of the following expression?
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [17]:
print(0 * np.nan) # O/P - nan
                  # np.nan means "Not a Number". NaN represents an undefined
                  # or unavailable numeric value.
print(np.nan == np.nan) # O/P - False.
                        # NaN is not equal to anything, including itself.
print(np.inf > np.nan)  # O/P - False.
                        # np.inf represents positive infinity.
                        # Comparisons involving NaN return False.
print(np.nan - np.nan)  # O/P - nan
                        # Arithmetic operations involving NaN generally result in NaN.
print(np.nan in set([np.nan]))  # O/P - True
                                # Set membership can identify the same NaN object
                                # even though np.nan == np.nan is False.
print(0.3 == 3 * 0.1)  # O/P - False.
                       # Due to floating-point precision, 3 * 0.1 is not represented
                       # exactly as 0.3.
                       # np.isclose(0.3, 3 * 0.1) can be used to check approximate equality.

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal.

In [18]:
np.diag([1, 2, 3, 4], k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern.

In [19]:
arr = np.ones((8,8),dtype = int)
arr[1::2,::2] = 0
arr[::2,1::2] = 0
arr

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [20]:
print(np.unravel_index(99,(6, 7, 8))) # finds the 3d index of element at index 99 in the array.

(np.int64(1), np.int64(5), np.int64(3))


#### 21. Create a checkerboard 8x8 matrix using the tile function.

In [21]:
np.tile(np.array([[1,0],[0,1]]),(4,4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix.

In [22]:
# Min-max normalization -
arr = np.random.randint(1,50,(5,5))
print(arr)
print()
arr = (arr - arr.min())/(arr.max() - arr.min())
print(arr)
print()

# Standardization (Z-score normalization) -
arr = np.random.randint(1,100,(5,5))
arr = (arr - np.mean(arr)) / np.std(arr)
print(arr)

[[19 29 23 18  1]
 [34 31 39 42  1]
 [ 1 21  3 10 12]
 [15 29 27 13  7]
 [ 4 39 38 20 28]]

[[0.43902439 0.68292683 0.53658537 0.41463415 0.        ]
 [0.80487805 0.73170732 0.92682927 1.         0.        ]
 [0.         0.48780488 0.04878049 0.2195122  0.26829268]
 [0.34146341 0.68292683 0.63414634 0.29268293 0.14634146]
 [0.07317073 0.92682927 0.90243902 0.46341463 0.65853659]]

[[ 1.13526962  1.40963661  0.03780167  1.04381396 -1.30354804]
 [-1.21209238  1.13526962  0.3731391  -0.38899142 -1.30354804]
 [-0.44996186  0.86090263  0.34265388 -0.6633584   1.47060705]
 [ 1.16575484  0.46459476  0.73896175  0.06828689 -1.09015149]
 [-0.90724017 -1.45597414  1.01332874 -0.96821061 -1.51694458]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA).

In [88]:
color_dtype = np.dtype([('R', np.uint8),('G', np.uint8),('B', np.uint8),('A', np.uint8)])
colors = np.array([(255, 0, 0, 255), (0, 255, 0, 255), (0, 0, 255, 255)], dtype=color_dtype)
print(colors.dtype)

[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product).

In [ ]:
arr1 = np.arange(1,16).reshape(5,3)
arr2 = np.ones((3,2),dtype = int)
print(arr1 @ arr2)
print()

# Alternative solution - 
arr = np.matmul(np.arange(1,16).reshape(5, 3), np.ones((3,2),dtype = int))
print(arr)

[[ 6  6]
 [15 15]
 [24 24]
 [33 33]
 [42 42]]

[[ 6  6]
 [15 15]
 [24 24]
 [33 33]
 [42 42]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [ ]:
arr = np.arange(-5,15)
print(arr)
arr[(arr > 3) & (arr < 8)]  *= -1
print(arr)

[-5 -4 -3 -2 -1  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[-5 -4 -3 -2 -1  0  1  2  3 -4 -5 -6 -7  8  9 10 11 12 13 14]


#### 26. What is the output of the following script?
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```


In [ ]:
print(sum(range(5), -1))    # O/P - 9
                            # Python's sum() → sum(iterable, start=0).
                            # The second argument (-1) is the starting value:
                            # 0 + 1 + 2 + 3 + 4 - 1 = 9.
from numpy import *         # Imports all public names from NumPy into the current namespace.
                            # This causes NumPy's sum() to shadow Python's built-in sum().
print(sum(range(5), -1))    # O/P - 10
                            # NumPy's sum() → equivalent to np.sum() → np.sum(a, axis=None, ...).
                            # Here, -1 is interpreted as axis=-1(last axis), not as a starting value.
import builtins
print(builtins.sum(range(5), -1))    # O/P - 9 -> Uses Python's sum().

10
10
9



#### 27. Consider an integer vector Z, which of these expressions are legal?
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [24]:
Z = 3
print(Z**Z)          # Legal. Calculates 3 raised to the power of 3. O/P - 27.
print(2 << Z >> 2)   # Legal. First calculates 2 << Z, then applies >> 2 to the result. O/P - 4.
print(Z <- Z)        # Legal. Interpreted as Z < (-Z). O/P - False.
print(1j * Z)        # Legal. Multiplies the complex number 1j by Z. O/P - 3j.
print(Z / 1 / 1)     # Legal. Calculates (Z / 1) / 1. O/P - 3.0.
print(Z < Z > Z)     # Legal. This is a chained comparison: (Z < Z) and (Z > Z). O/P - False.

27
4
False
3j
3.0
False



#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))  # Equivalent to 0 / 0. O/P - nan. And raises a RuntimeWarning.
print(np.array(0) // np.array(0))  # Equivalent to 0 // 0. O/P - 0.
                    # NumPy's floor division by zero produces 0 for integer arrays and raises a RuntimeWarning.
np.array([np.nan]).astype(int).astype(float)
                                # O/P - *some float value that does not represent nan.*
                                # Converting NaN directly to an integer is invalid; NumPy uses
                                # the minimum representable integer value, with a RuntimeWarning.
                                # Converting that integer back to float doesn't  restore NaN.

nan
0
[-9.22337204e+18]


C:\Users\Ravi\AppData\Local\Temp\ipykernel_20608\3701397783.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))  # Equivalent to 0 / 0. O/P - nan
C:\Users\Ravi\AppData\Local\Temp\ipykernel_20608\3701397783.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))  # Equivalent to 0 // 0. O/P - nan
C:\Users\Ravi\AppData\Local\Temp\ipykernel_20608\3701397783.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float)) # Creates a 1-D array with value nan.


### `NaN` and Integer Conversion

```python
np.array([np.nan]).astype(int).astype(float)
```

> **Remember:**
>
> - `NaN` can be represented by floating-point dtypes, but **not by integer dtypes**.
> - Converting `NaN` to `int` produces a `RuntimeWarning` and typically converts it to the minimum representable integer value.
> - Converting that integer back to `float` **does not restore `NaN`**.
>
> ```text
> [NaN] → astype(int) → [-9223372036854775808] → astype(float) → [-9.22337204e+18]
> ```

#### 29. How to round away from zero in a float array ?

In [ ]:
arr = np.array([1.2,1.8,-1.2,-1.8,0.0])
print(arr)
print(np.sign(arr)*np.ceil(np.abs(arr)))

# Another way - 
print(np.copysign(np.ceil(np.abs(Z)), Z))

# Another way (Not as efficient) - 
np.where(Z > 0, np.ceil(Z), np.floor(Z))

[ 1.2  1.8 -1.2 -1.8  0. ]
[ 2.  2. -2. -2.  0.]


#### 30. How to find common values between two arrays?

In [33]:
arr1 = np.arange(1,8)
arr2 = np.arange(4,9)
np.intersect1d(arr1,arr2)


array([4, 5, 6, 7])

#### 31. How to ignore all numpy warnings (not recommended)?

In [39]:
np.seterr(all='ignore')
print(np.array(3) / np.array(0)) # Prints inf. 
                                # Note - print(3/0) will still raise error as 3/0 is ordinary python division.
np.seterr(all='warn')

# For temporary change we can do - 
with np.errstate(all="ignore"):
    print(np.array(3) / 0)
# Once the block ends, the previous settings are automatically restored.

inf
inf



#### 32. Is the following expressions true?
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
print(np.sqrt(-1))          # O/P - nan. For non-real output, it returns nan.
                            # Also, np.sqrt(-1) will normally produce a RuntimeWarning about an invalid value.
print(np.emath.sqrt(-1))    # O/P - 1j. Designed to handle complex numbers and returns 1j in this case.
print(np.sqrt(-1) == np.emath.sqrt(-1)) # O/P - False.

nan
1j
False


C:\Users\Ravi\AppData\Local\Temp\ipykernel_20608\801529985.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1))              # O/P - nan. For negative real numbers, it returns nan for all complex o/p.
C:\Users\Ravi\AppData\Local\Temp\ipykernel_20608\801529985.py:3: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1)) # O/P - False.


#### 33. How to get the dates of yesterday, today and tomorrow?

In [ ]:
import datetime     # python's datetime module
today = datetime.date.today()
print("Yesterday was :", today - datetime.timedelta(days=1))
print("Today is :",today)
print("Tomorrow will be :", today + datetime.timedelta(days=1))

# Another way to write above code  -
from datetime import date, timedelta  # only imports the functions needed
today = date.today()
print("Yesterday was :", today - timedelta(days=1))
print("Today is :",today)
print("Tomorrow will be :", today + timedelta(days=1))

# Another solution (without using Python's datetime module) -
yesterday = np.datetime64('today') - np.timedelta64(1, 'D')
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1, 'D')


Yesterday was : 2026-08-12
Today is : 2026-08-13
Tomorrow will be : 2026-08-14
Yesterday was : 2026-08-12
Today is : 2026-08-13
Tomorrow will be : 2026-08-14


#### 34. How to get all the dates corresponding to the month of July 2016?

In [56]:
arr = np.arange('2016-07','2016-08',dtype='datetime64[D]')
print(arr)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)?

In [66]:
A = np.arange(1,7,dtype=float)
B = np.ones(6)
print(A)
print(B)
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)
print(A)


[1. 2. 3. 4. 5. 6.]
[1. 1. 1. 1. 1. 1.]
[ -1.  -3.  -6. -10. -15. -21.]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods.

In [87]:
arr = np.random.uniform(1,100,(3,3))
print(arr)
print(arr//1)
print(arr-arr%1)
print(np.floor(arr))
print(arr.astype(int))
print(np.trunc(arr))

[[ 4.16460057 13.29751474 62.21641639]
 [20.27158246 87.22643418 81.30181351]
 [ 9.38880653 40.93837925 45.55184613]]
[[ 4. 13. 62.]
 [20. 87. 81.]
 [ 9. 40. 45.]]
[[ 4. 13. 62.]
 [20. 87. 81.]
 [ 9. 40. 45.]]
[[ 4. 13. 62.]
 [20. 87. 81.]
 [ 9. 40. 45.]]
[[ 4 13 62]
 [20 87 81]
 [ 9 40 45]]
[[ 4. 13. 62.]
 [20. 87. 81.]
 [ 9. 40. 45.]]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4.

In [89]:
arr = np.arange(0,5)
np.resize(arr)

TypeError: resize() missing 1 required positional argument: 'new_shape'

#### 38. Consider a generator function that generates 10 integers and use it to build an array.

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded.

#### 40. Create a random vector of size 10 and sort it.

#### 41. How to sum a small array faster than np.sum? 

#### 42. Consider two random arrays A and B, check if they are equal.

#### 43. Make an array immutable (read-only).

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates.

#### 45. Create random vector of size 10 and replace the maximum value by 0.