#### 1. Import the numpy package under the name `np`.

In [79]:
import numpy as np

#### 2. Print the numpy version and the configuration

In [80]:
print(np.__version__)
np.show_config()

2.5.1
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-h1i__5an/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-h1i__5an/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.33.112.0  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=24
    pc file directory: D:/a/numpy-release/numpy-release/.openblas
    version: 0.3.33.112.0
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-h1i__5an/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-h1i__5an/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas 

#### 3. Create a null vector of size 10.

In [81]:
arr = np.zeros(10,int)
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 4. How to find the memory size of any array.

In [82]:
print(arr.nbytes)

80


#### 5. How to get the documentation of the numpy add function from the command line?

In [83]:
np.info(np.add)

# Another(older) way of doing it -
!python -c "import numpy; numpy.info(numpy.add)"

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 10 but the fifth value which is 1.

In [84]:
arr = np.zeros(10)
arr[4]=1
print(arr)

# Another way of doing it - 
np.eye(10,dtype = int)[4]  # returns the 4th row of 10x10 identity matrix, in which 5th element is 1 and rest are 0.

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

#### 7. Create a vector with values ranging from 10 to 49.

In [85]:
arr = np.arange(10,50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last).

In [86]:
arr = np.arange(50)
print(arr)
arr = arr[::-1]
arr

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8

In [87]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0].

In [88]:
print(np.argwhere(np.array([1,2,0,0,4,0]) != 0))

# Alternative (better) way of doing it - 
np.nonzero(np.array([1,2,0,0,4,0]))

[[0]
 [1]
 [4]]


(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix.

In [89]:
arr = np.identity(3,int)
arr

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

#### 12. Create a 3x3x3 array with random values.

In [90]:
arr = np.random.random((3,3,3))
arr

array([[[0.308667  , 0.40030916, 0.33500049],
        [0.22974399, 0.14816063, 0.58721547],
        [0.08336208, 0.52565686, 0.28579752]],

       [[0.24520954, 0.76834148, 0.14331272],
        [0.69245729, 0.63463371, 0.9757459 ],
        [0.12957865, 0.15974937, 0.0279855 ]],

       [[0.44190779, 0.8235807 , 0.32800664],
        [0.80042977, 0.91552185, 0.92826488],
        [0.68809411, 0.14117915, 0.07930529]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values.

In [91]:
arr = np.random.random((10,10))
print("min = ", np.min(arr))   # can also be written as : print("min = ", arr.min())
print("max = ", np.max(arr))

min =  0.0004569505227199899
max =  0.9697164255720632


#### 14. Create a random vector of size 30 and find the mean value.

In [92]:
arr = np.random.random(30)
np.mean(arr)

np.float64(0.5040154560325214)

#### 15. Create a 2d array with 1 on the border and 0 inside.

In [93]:
arr = np.ones((5,6),dtype= int)
arr[1:-1,1:-1] = 0
print(arr)
print()
# Another way to do this is - 
arr = np.zeros((5,6),dtype= int)
arr[0, :] = arr[-1, :] = 1
arr[:, 0] = arr[:, -1] = 1
print(arr)

[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]

[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [94]:
arr = np.arange(1,16).reshape(3,5)
print(arr)
np.pad(arr, pad_width=1, mode='constant', constant_values=0)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


array([[ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5,  0],
       [ 0,  6,  7,  8,  9, 10,  0],
       [ 0, 11, 12, 13, 14, 15,  0],
       [ 0,  0,  0,  0,  0,  0,  0]])

#### 17. What is the result of the following expression?
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [95]:
print(0 * np.nan) # O/P - nan
                  # np.nan means "Not a Number". NaN represents an undefined
                  # or unavailable numeric value.
print(np.nan == np.nan) # O/P - False.
                        # NaN is not equal to anything, including itself.
print(np.inf > np.nan)  # O/P - False.
                        # np.inf represents positive infinity.
                        # Comparisons involving NaN return False.
print(np.nan - np.nan)  # O/P - nan
                        # Arithmetic operations involving NaN generally result in NaN.
print(np.nan in set([np.nan]))  # O/P - True
                                # Set membership can identify the same NaN object
                                # even though np.nan == np.nan is False.
print(0.3 == 3 * 0.1)  # O/P - False.
                       # Due to floating-point precision, 3 * 0.1 is not represented
                       # exactly as 0.3.
                       # np.isclose(0.3, 3 * 0.1) can be used to check approximate equality.

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal.

In [96]:
np.diag([1, 2, 3, 4], k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern.

In [97]:
arr = np.ones((8,8),dtype = int)
arr[1::2,::2] = 0
arr[::2,1::2] = 0
arr

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [98]:
print(np.unravel_index(99,(6, 7, 8))) # finds the 3d index of element at index 99 in the array.

(np.int64(1), np.int64(5), np.int64(3))


#### 21. Create a checkerboard 8x8 matrix using the tile function.

In [99]:
np.tile(np.array([[1,0],[0,1]]),(4,4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix.

In [100]:
# Min-max normalization -
arr = np.random.randint(1,50,(5,5))
print(arr)
print()
arr = (arr - arr.min())/(arr.max() - arr.min())
print(arr)
print()

# Standardization (Z-score normalization) -
arr = np.random.randint(1,100,(5,5))
arr = (arr - np.mean(arr)) / np.std(arr)
print(arr)

[[24 47 43 27 40]
 [35 33 24  2 27]
 [45 39 24 13 29]
 [36  6 49 22  6]
 [21 20  8 10  4]]

[[0.46808511 0.95744681 0.87234043 0.53191489 0.80851064]
 [0.70212766 0.65957447 0.46808511 0.         0.53191489]
 [0.91489362 0.78723404 0.46808511 0.23404255 0.57446809]
 [0.72340426 0.08510638 1.         0.42553191 0.08510638]
 [0.40425532 0.38297872 0.12765957 0.17021277 0.04255319]]

[[-1.63746363  1.19075079 -0.07831978  1.77089733 -1.23861288]
 [ 0.39304928  0.79190004 -0.65846633 -0.44091138  1.37204658]
 [-1.38364951 -0.91228044  1.08197331 -1.1298354   0.50182676]
 [-0.69472549  1.04571415 -1.20235372 -0.1508381  -0.76724381]
 [ 1.11823247 -0.22335642  1.15449163  0.82815919 -0.73098465]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA).

In [101]:
color_dtype = np.dtype([('R', np.uint8),('G', np.uint8),('B', np.uint8),('A', np.uint8)])
print(colors['R'])
colors = np.array([(255, 0, 0, 255), (0, 255, 0, 255), (0, 0, 255, 255)], dtype=color_dtype)
print(colors.dtype)

[255   0   0]
[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product).

In [102]:
arr1 = np.arange(1,16).reshape(5,3)
arr2 = np.ones((3,2),dtype = int)
print(arr1 @ arr2)
print()

# Alternative solution - 
arr = np.matmul(np.arange(1,16).reshape(5, 3), np.ones((3,2),dtype = int))
print(arr)

[[ 6  6]
 [15 15]
 [24 24]
 [33 33]
 [42 42]]

[[ 6  6]
 [15 15]
 [24 24]
 [33 33]
 [42 42]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [103]:
arr = np.arange(-5,15)
print(arr)
arr[(arr > 3) & (arr < 8)]  *= -1
print(arr)

[-5 -4 -3 -2 -1  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[-5 -4 -3 -2 -1  0  1  2  3 -4 -5 -6 -7  8  9 10 11 12 13 14]


#### 26. What is the output of the following script?
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```


In [104]:
print(sum(range(5), -1))    # O/P - 9
                            # Python's sum() → sum(iterable, start=0).
                            # The second argument (-1) is the starting value:
                            # 0 + 1 + 2 + 3 + 4 - 1 = 9.
from numpy import *         # Imports all public names from NumPy into the current namespace.
                            # This causes NumPy's sum() to shadow Python's built-in sum().
print(sum(range(5), -1))    # O/P - 10
                            # NumPy's sum() → equivalent to np.sum() → np.sum(a, axis=None, ...).
                            # Here, -1 is interpreted as axis=-1(last axis), not as a starting value.
print(builtin.sum(range(5), -1))    # O/P - 9 -> Uses Python's sum().

10
10


NameError: name 'builtin' is not defined