#### 1. Import the numpy package under the name `np`.

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration

In [ ]:
print(np.__version__)
np.show_config()

2.5.1
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-h1i__5an/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-h1i__5an/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.33.112.0  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=24
    pc file directory: D:/a/numpy-release/numpy-release/.openblas
    version: 0.3.33.112.0
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-h1i__5an/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-h1i__5an/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas 

#### 3. Create a null vector of size 10.

In [10]:
arr = np.zeros(10,int)
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 4. How to find the memory size of any array.

In [13]:
print(arr.nbytes)

80


#### 5. How to get the documentation of the numpy add function from the command line?

In [40]:
np.info(np.add)

# Another(older) way of doing it -
!python -c "import numpy; numpy.info(numpy.add)"

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 10 but the fifth value which is 1.

In [44]:
arr = np.zeros(10)
arr[4]=1
print(arr)

# Another way of doing it - 
np.eye(10,dtype = int)[4]  # returns the 4th row of 10x10 identity matrix, in which 5th element is 1 and rest are 0.

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

#### 7. Create a vector with values ranging from 10 to 49.

In [14]:
arr = np.arange(10,50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last).

In [46]:
arr = np.arange(50)
print(arr)
arr = arr[::-1]
arr

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0].

In [50]:
print(np.argwhere(np.array([1,2,0,0,4,0]) != 0))

# Alternative (better) way of doing it - 
np.nonzero(np.array([1,2,0,0,4,0]))

[[0]
 [1]
 [4]]


(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix.

In [23]:
arr = np.identity(3,int)
arr

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

#### 12. Create a 3x3x3 array with random values.

In [52]:
arr = np.random.random((3,3,3))
arr

array([[[0.35591969, 0.7179676 , 0.63887805],
        [0.1176588 , 0.96635526, 0.41698127],
        [0.44673341, 0.95145589, 0.80079155]],

       [[0.12033511, 0.12606904, 0.93306983],
        [0.62594575, 0.00442419, 0.83383233],
        [0.8143778 , 0.26940763, 0.88293147]],

       [[0.33076947, 0.63857551, 0.48453835],
        [0.06526626, 0.7449307 , 0.90088772],
        [0.41049885, 0.93467453, 0.79425027]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values.

In [56]:
arr = np.random.random((10,10))
print("min = ", np.min(arr))   # can also be written as : print("min = ", arr.min())
print("max = ", np.max(arr))

min =  0.0018707504066406422
max =  0.9911317152081826


#### 14. Create a random vector of size 30 and find the mean value.

In [33]:
arr = np.random.random(30)
np.mean(arr)

np.float64(0.5195932237645934)

#### 15. Create a 2d array with 1 on the border and 0 inside.

In [72]:
arr = np.ones((5,6),dtype= int)
arr[1:-1,1:-1] = 0
print(arr)
print()
# Another way to do this is - 
arr = np.zeros((5,6),dtype= int)
arr[0, :] = arr[-1, :] = 1
arr[:, 0] = arr[:, -1] = 1
print(arr)

[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]

[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [65]:
arr = np.arange(1,16).reshape(3,5)
print(arr)
np.pad(arr, pad_width=1, mode='constant', constant_values=0)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


array([[ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5,  0],
       [ 0,  6,  7,  8,  9, 10,  0],
       [ 0, 11, 12, 13, 14, 15,  0],
       [ 0,  0,  0,  0,  0,  0,  0]])

#### 17. What is the result of the following expression?
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan) # O/P - nan
                  # np.nan means "Not a Number". NaN represents an undefined
                  # or unavailable numeric value.
print(np.nan == np.nan) # O/P - False.
                        # NaN is not equal to anything, including itself.
print(np.inf > np.nan)  # O/P - False.
                        # np.inf represents positive infinity.
                        # Comparisons involving NaN return False.
print(np.nan - np.nan)  # O/P - nan
                        # Arithmetic operations involving NaN generally result in NaN.
print(np.nan in set([np.nan]))  # O/P - True
                                # Set membership can identify the same NaN object
                                # even though np.nan == np.nan is False.
print(0.3 == 3 * 0.1)  # O/P - False.
                       # Due to floating-point precision, 3 * 0.1 is not represented
                       # exactly as 0.3.
                       # np.isclose(0.3, 3 * 0.1) can be used to check approximate equality.

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal.

In [80]:
np.diag([1, 2, 3, 4], k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern.

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

#### 21. Create a checkerboard 8x8 matrix using the tile function.

#### 22. Normalize a 5x5 random matrix.

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA).

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product).

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place.